default:
  has_layout:     true
  layout:         layout

batchReporteMasVendidosSuccess:
  has_layout:     true
  layout:         layout_print

batchReporteAbcSuccess:
  has_layout:     true
  layout:         layout_print