<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CajaDet', 'doctrine');

/**
 * BaseCajaDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $caja_id
 * @property integer $sf_guard_user_id
 * @property timestamp $fecha
 * @property boolean $status
 * @property string $fondo
 * @property string $descripcion
 * @property Caja $Caja
 * 
 * @method integer   getId()               Returns the current record's "id" value
 * @method integer   getCajaId()           Returns the current record's "caja_id" value
 * @method integer   getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method timestamp getFecha()            Returns the current record's "fecha" value
 * @method boolean   getStatus()           Returns the current record's "status" value
 * @method string    getFondo()            Returns the current record's "fondo" value
 * @method string    getDescripcion()      Returns the current record's "descripcion" value
 * @method Caja      getCaja()             Returns the current record's "Caja" value
 * @method CajaDet   setId()               Sets the current record's "id" value
 * @method CajaDet   setCajaId()           Sets the current record's "caja_id" value
 * @method CajaDet   setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method CajaDet   setFecha()            Sets the current record's "fecha" value
 * @method CajaDet   setStatus()           Sets the current record's "status" value
 * @method CajaDet   setFondo()            Sets the current record's "fondo" value
 * @method CajaDet   setDescripcion()      Sets the current record's "descripcion" value
 * @method CajaDet   setCaja()             Sets the current record's "Caja" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCajaDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('caja_det');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('caja_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('fondo', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Caja', array(
             'local' => 'caja_id',
             'foreign' => 'id'));
    }
}