<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Inexistencia', 'doctrine');

/**
 * BaseInexistencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $sf_guard_user_id
 * @property date $fecha
 * 
 * @method integer      getId()               Returns the current record's "id" value
 * @method string       getNombre()           Returns the current record's "nombre" value
 * @method integer      getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method date         getFecha()            Returns the current record's "fecha" value
 * @method Inexistencia setId()               Sets the current record's "id" value
 * @method Inexistencia setNombre()           Sets the current record's "nombre" value
 * @method Inexistencia setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Inexistencia setFecha()            Sets the current record's "fecha" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInexistencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inexistencia');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}