<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Factura', 'doctrine');

/**
 * BaseFactura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $fecha
 * @property string $dias_credito
 * @property integer $empresa_id
 * @property integer $deposito_id
 * @property integer $cliente_id
 * @property integer $nota_entrega_id
 * @property integer $orden_compra_id
 * @property integer $caja_id
 * @property string $razon_social
 * @property string $doc_id
 * @property string $telf
 * @property string $direccion
 * @property string $direccion_entrega
 * @property string $ncontrol
 * @property string $num_factura
 * @property string $num_fact_fiscal
 * @property string $codigof
 * @property string $ndespacho
 * @property string $forma_pago
 * @property string $tasa_cambio
 * @property string $subtotal
 * @property string $subtotal_desc
 * @property string $iva
 * @property string $base_imponible
 * @property string $iva_monto
 * @property string $total
 * @property string $total2
 * @property string $descuento
 * @property string $monto_faltante
 * @property string $monto_pagado
 * @property boolean $has_invoice
 * @property integer $estatus
 * @property NotaEntrega $NotaEntrega
 * @property OrdenCompra $OrdenCompra
 * @property Cliente $Cliente
 * @property Empresa $Empresa
 * @property InvDeposito $InvDeposito
 * @property Doctrine_Collection $FacturaDet
 * @property Doctrine_Collection $CuentasCobrar
 * @property Caja $Caja
 * @property Doctrine_Collection $AlmacenTransito
 * @property Doctrine_Collection $Devolver
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method date                getFecha()             Returns the current record's "fecha" value
 * @method string              getDiasCredito()       Returns the current record's "dias_credito" value
 * @method integer             getEmpresaId()         Returns the current record's "empresa_id" value
 * @method integer             getDepositoId()        Returns the current record's "deposito_id" value
 * @method integer             getClienteId()         Returns the current record's "cliente_id" value
 * @method integer             getNotaEntregaId()     Returns the current record's "nota_entrega_id" value
 * @method integer             getOrdenCompraId()     Returns the current record's "orden_compra_id" value
 * @method integer             getCajaId()            Returns the current record's "caja_id" value
 * @method string              getRazonSocial()       Returns the current record's "razon_social" value
 * @method string              getDocId()             Returns the current record's "doc_id" value
 * @method string              getTelf()              Returns the current record's "telf" value
 * @method string              getDireccion()         Returns the current record's "direccion" value
 * @method string              getDireccionEntrega()  Returns the current record's "direccion_entrega" value
 * @method string              getNcontrol()          Returns the current record's "ncontrol" value
 * @method string              getNumFactura()        Returns the current record's "num_factura" value
 * @method string              getNumFactFiscal()     Returns the current record's "num_fact_fiscal" value
 * @method string              getCodigof()           Returns the current record's "codigof" value
 * @method string              getNdespacho()         Returns the current record's "ndespacho" value
 * @method string              getFormaPago()         Returns the current record's "forma_pago" value
 * @method string              getTasaCambio()        Returns the current record's "tasa_cambio" value
 * @method string              getSubtotal()          Returns the current record's "subtotal" value
 * @method string              getSubtotalDesc()      Returns the current record's "subtotal_desc" value
 * @method string              getIva()               Returns the current record's "iva" value
 * @method string              getBaseImponible()     Returns the current record's "base_imponible" value
 * @method string              getIvaMonto()          Returns the current record's "iva_monto" value
 * @method string              getTotal()             Returns the current record's "total" value
 * @method string              getTotal2()            Returns the current record's "total2" value
 * @method string              getDescuento()         Returns the current record's "descuento" value
 * @method string              getMontoFaltante()     Returns the current record's "monto_faltante" value
 * @method string              getMontoPagado()       Returns the current record's "monto_pagado" value
 * @method boolean             getHasInvoice()        Returns the current record's "has_invoice" value
 * @method integer             getEstatus()           Returns the current record's "estatus" value
 * @method NotaEntrega         getNotaEntrega()       Returns the current record's "NotaEntrega" value
 * @method OrdenCompra         getOrdenCompra()       Returns the current record's "OrdenCompra" value
 * @method Cliente             getCliente()           Returns the current record's "Cliente" value
 * @method Empresa             getEmpresa()           Returns the current record's "Empresa" value
 * @method InvDeposito         getInvDeposito()       Returns the current record's "InvDeposito" value
 * @method Doctrine_Collection getFacturaDet()        Returns the current record's "FacturaDet" collection
 * @method Doctrine_Collection getCuentasCobrar()     Returns the current record's "CuentasCobrar" collection
 * @method Caja                getCaja()              Returns the current record's "Caja" value
 * @method Doctrine_Collection getAlmacenTransito()   Returns the current record's "AlmacenTransito" collection
 * @method Doctrine_Collection getDevolver()          Returns the current record's "Devolver" collection
 * @method Factura             setId()                Sets the current record's "id" value
 * @method Factura             setFecha()             Sets the current record's "fecha" value
 * @method Factura             setDiasCredito()       Sets the current record's "dias_credito" value
 * @method Factura             setEmpresaId()         Sets the current record's "empresa_id" value
 * @method Factura             setDepositoId()        Sets the current record's "deposito_id" value
 * @method Factura             setClienteId()         Sets the current record's "cliente_id" value
 * @method Factura             setNotaEntregaId()     Sets the current record's "nota_entrega_id" value
 * @method Factura             setOrdenCompraId()     Sets the current record's "orden_compra_id" value
 * @method Factura             setCajaId()            Sets the current record's "caja_id" value
 * @method Factura             setRazonSocial()       Sets the current record's "razon_social" value
 * @method Factura             setDocId()             Sets the current record's "doc_id" value
 * @method Factura             setTelf()              Sets the current record's "telf" value
 * @method Factura             setDireccion()         Sets the current record's "direccion" value
 * @method Factura             setDireccionEntrega()  Sets the current record's "direccion_entrega" value
 * @method Factura             setNcontrol()          Sets the current record's "ncontrol" value
 * @method Factura             setNumFactura()        Sets the current record's "num_factura" value
 * @method Factura             setNumFactFiscal()     Sets the current record's "num_fact_fiscal" value
 * @method Factura             setCodigof()           Sets the current record's "codigof" value
 * @method Factura             setNdespacho()         Sets the current record's "ndespacho" value
 * @method Factura             setFormaPago()         Sets the current record's "forma_pago" value
 * @method Factura             setTasaCambio()        Sets the current record's "tasa_cambio" value
 * @method Factura             setSubtotal()          Sets the current record's "subtotal" value
 * @method Factura             setSubtotalDesc()      Sets the current record's "subtotal_desc" value
 * @method Factura             setIva()               Sets the current record's "iva" value
 * @method Factura             setBaseImponible()     Sets the current record's "base_imponible" value
 * @method Factura             setIvaMonto()          Sets the current record's "iva_monto" value
 * @method Factura             setTotal()             Sets the current record's "total" value
 * @method Factura             setTotal2()            Sets the current record's "total2" value
 * @method Factura             setDescuento()         Sets the current record's "descuento" value
 * @method Factura             setMontoFaltante()     Sets the current record's "monto_faltante" value
 * @method Factura             setMontoPagado()       Sets the current record's "monto_pagado" value
 * @method Factura             setHasInvoice()        Sets the current record's "has_invoice" value
 * @method Factura             setEstatus()           Sets the current record's "estatus" value
 * @method Factura             setNotaEntrega()       Sets the current record's "NotaEntrega" value
 * @method Factura             setOrdenCompra()       Sets the current record's "OrdenCompra" value
 * @method Factura             setCliente()           Sets the current record's "Cliente" value
 * @method Factura             setEmpresa()           Sets the current record's "Empresa" value
 * @method Factura             setInvDeposito()       Sets the current record's "InvDeposito" value
 * @method Factura             setFacturaDet()        Sets the current record's "FacturaDet" collection
 * @method Factura             setCuentasCobrar()     Sets the current record's "CuentasCobrar" collection
 * @method Factura             setCaja()              Sets the current record's "Caja" value
 * @method Factura             setAlmacenTransito()   Sets the current record's "AlmacenTransito" collection
 * @method Factura             setDevolver()          Sets the current record's "Devolver" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFactura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('factura');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('dias_credito', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('deposito_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cliente_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('nota_entrega_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('orden_compra_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('caja_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('razon_social', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('doc_id', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('telf', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('direccion_entrega', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('ncontrol', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('num_factura', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('num_fact_fiscal', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('codigof', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('ndespacho', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('forma_pago', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('tasa_cambio', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('subtotal', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('subtotal_desc', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('iva', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('base_imponible', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('iva_monto', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('total', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('total2', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('descuento', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 0,
             'length' => 20,
             ));
        $this->hasColumn('monto_faltante', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('monto_pagado', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('has_invoice', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('estatus', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NotaEntrega', array(
             'local' => 'nota_entrega_id',
             'foreign' => 'id'));

        $this->hasOne('OrdenCompra', array(
             'local' => 'orden_compra_id',
             'foreign' => 'id'));

        $this->hasOne('Cliente', array(
             'local' => 'cliente_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('InvDeposito', array(
             'local' => 'deposito_id',
             'foreign' => 'id'));

        $this->hasMany('FacturaDet', array(
             'local' => 'id',
             'foreign' => 'factura_id'));

        $this->hasMany('CuentasCobrar', array(
             'local' => 'id',
             'foreign' => 'factura_id'));

        $this->hasOne('Caja', array(
             'local' => 'caja_id',
             'foreign' => 'id'));

        $this->hasMany('AlmacenTransito', array(
             'local' => 'id',
             'foreign' => 'factura_id'));

        $this->hasMany('Devolver', array(
             'local' => 'id',
             'foreign' => 'factura_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}