<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DevolverDet', 'doctrine');

/**
 * BaseDevolverDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $devolver_id
 * @property string $qty
 * @property string $price_unit
 * @property string $price_tot
 * @property integer $inventario_id
 * @property integer $oferta_id
 * @property string $descripcion
 * @property string $exento
 * @property string $tasa_cambio
 * @property Devolver $Devolver
 * @property Inventario $Inventario
 * @property Oferta $Oferta
 * 
 * @method integer     getId()            Returns the current record's "id" value
 * @method integer     getDevolverId()    Returns the current record's "devolver_id" value
 * @method string      getQty()           Returns the current record's "qty" value
 * @method string      getPriceUnit()     Returns the current record's "price_unit" value
 * @method string      getPriceTot()      Returns the current record's "price_tot" value
 * @method integer     getInventarioId()  Returns the current record's "inventario_id" value
 * @method integer     getOfertaId()      Returns the current record's "oferta_id" value
 * @method string      getDescripcion()   Returns the current record's "descripcion" value
 * @method string      getExento()        Returns the current record's "exento" value
 * @method string      getTasaCambio()    Returns the current record's "tasa_cambio" value
 * @method Devolver    getDevolver()      Returns the current record's "Devolver" value
 * @method Inventario  getInventario()    Returns the current record's "Inventario" value
 * @method Oferta      getOferta()        Returns the current record's "Oferta" value
 * @method DevolverDet setId()            Sets the current record's "id" value
 * @method DevolverDet setDevolverId()    Sets the current record's "devolver_id" value
 * @method DevolverDet setQty()           Sets the current record's "qty" value
 * @method DevolverDet setPriceUnit()     Sets the current record's "price_unit" value
 * @method DevolverDet setPriceTot()      Sets the current record's "price_tot" value
 * @method DevolverDet setInventarioId()  Sets the current record's "inventario_id" value
 * @method DevolverDet setOfertaId()      Sets the current record's "oferta_id" value
 * @method DevolverDet setDescripcion()   Sets the current record's "descripcion" value
 * @method DevolverDet setExento()        Sets the current record's "exento" value
 * @method DevolverDet setTasaCambio()    Sets the current record's "tasa_cambio" value
 * @method DevolverDet setDevolver()      Sets the current record's "Devolver" value
 * @method DevolverDet setInventario()    Sets the current record's "Inventario" value
 * @method DevolverDet setOferta()        Sets the current record's "Oferta" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDevolverDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('devolver_det');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('devolver_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('qty', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 1,
             'length' => 20,
             ));
        $this->hasColumn('price_unit', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('price_tot', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('inventario_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('oferta_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('exento', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('tasa_cambio', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Devolver', array(
             'local' => 'devolver_id',
             'foreign' => 'id'));

        $this->hasOne('Inventario', array(
             'local' => 'inventario_id',
             'foreign' => 'id'));

        $this->hasOne('Oferta', array(
             'local' => 'oferta_id',
             'foreign' => 'id'));
    }
}