<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NotaDebitoDet', 'doctrine');

/**
 * BaseNotaDebitoDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nota_debito_id
 * @property integer $cuentas_pagar_id
 * @property string $monto
 * @property string $descripcion
 * @property boolean $anulado
 * @property NotaDebito $NotaDebito
 * @property CuentasPagar $CuentasPagar
 * 
 * @method integer       getId()               Returns the current record's "id" value
 * @method integer       getNotaDebitoId()     Returns the current record's "nota_debito_id" value
 * @method integer       getCuentasPagarId()   Returns the current record's "cuentas_pagar_id" value
 * @method string        getMonto()            Returns the current record's "monto" value
 * @method string        getDescripcion()      Returns the current record's "descripcion" value
 * @method boolean       getAnulado()          Returns the current record's "anulado" value
 * @method NotaDebito    getNotaDebito()       Returns the current record's "NotaDebito" value
 * @method CuentasPagar  getCuentasPagar()     Returns the current record's "CuentasPagar" value
 * @method NotaDebitoDet setId()               Sets the current record's "id" value
 * @method NotaDebitoDet setNotaDebitoId()     Sets the current record's "nota_debito_id" value
 * @method NotaDebitoDet setCuentasPagarId()   Sets the current record's "cuentas_pagar_id" value
 * @method NotaDebitoDet setMonto()            Sets the current record's "monto" value
 * @method NotaDebitoDet setDescripcion()      Sets the current record's "descripcion" value
 * @method NotaDebitoDet setAnulado()          Sets the current record's "anulado" value
 * @method NotaDebitoDet setNotaDebito()       Sets the current record's "NotaDebito" value
 * @method NotaDebitoDet setCuentasPagar()     Sets the current record's "CuentasPagar" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotaDebitoDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nota_debito_det');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nota_debito_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cuentas_pagar_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('monto', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('anulado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NotaDebito', array(
             'local' => 'nota_debito_id',
             'foreign' => 'id'));

        $this->hasOne('CuentasPagar', array(
             'local' => 'cuentas_pagar_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}