<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OrdenesCompraDet', 'doctrine');

/**
 * BaseOrdenesCompraDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ordenes_compra_id
 * @property string $qty
 * @property string $price_unit
 * @property string $price_tot
 * @property integer $producto_id
 * @property OrdenesCompra $OrdenesCompra
 * @property Producto $Producto
 * 
 * @method integer          getId()                Returns the current record's "id" value
 * @method integer          getOrdenesCompraId()   Returns the current record's "ordenes_compra_id" value
 * @method string           getQty()               Returns the current record's "qty" value
 * @method string           getPriceUnit()         Returns the current record's "price_unit" value
 * @method string           getPriceTot()          Returns the current record's "price_tot" value
 * @method integer          getProductoId()        Returns the current record's "producto_id" value
 * @method OrdenesCompra    getOrdenesCompra()     Returns the current record's "OrdenesCompra" value
 * @method Producto         getProducto()          Returns the current record's "Producto" value
 * @method OrdenesCompraDet setId()                Sets the current record's "id" value
 * @method OrdenesCompraDet setOrdenesCompraId()   Sets the current record's "ordenes_compra_id" value
 * @method OrdenesCompraDet setQty()               Sets the current record's "qty" value
 * @method OrdenesCompraDet setPriceUnit()         Sets the current record's "price_unit" value
 * @method OrdenesCompraDet setPriceTot()          Sets the current record's "price_tot" value
 * @method OrdenesCompraDet setProductoId()        Sets the current record's "producto_id" value
 * @method OrdenesCompraDet setOrdenesCompra()     Sets the current record's "OrdenesCompra" value
 * @method OrdenesCompraDet setProducto()          Sets the current record's "Producto" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdenesCompraDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ordenes_compra_det');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ordenes_compra_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('qty', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 1,
             'length' => 20,
             ));
        $this->hasColumn('price_unit', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('price_tot', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('producto_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OrdenesCompra', array(
             'local' => 'ordenes_compra_id',
             'foreign' => 'id'));

        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));
    }
}