<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('InvEntrada', 'doctrine');

/**
 * BaseInvEntrada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $deposito_id
 * @property string $ncontrol
 * @property string $tasa_cambio
 * @property string $total
 * @property boolean $anulado
 * @property string $descripcion
 * @property Empresa $Empresa
 * @property InvDeposito $InvDeposito
 * @property Doctrine_Collection $InvEntradaDet
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getEmpresaId()     Returns the current record's "empresa_id" value
 * @method integer             getDepositoId()    Returns the current record's "deposito_id" value
 * @method string              getNcontrol()      Returns the current record's "ncontrol" value
 * @method string              getTasaCambio()    Returns the current record's "tasa_cambio" value
 * @method string              getTotal()         Returns the current record's "total" value
 * @method boolean             getAnulado()       Returns the current record's "anulado" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method Empresa             getEmpresa()       Returns the current record's "Empresa" value
 * @method InvDeposito         getInvDeposito()   Returns the current record's "InvDeposito" value
 * @method Doctrine_Collection getInvEntradaDet() Returns the current record's "InvEntradaDet" collection
 * @method InvEntrada          setId()            Sets the current record's "id" value
 * @method InvEntrada          setEmpresaId()     Sets the current record's "empresa_id" value
 * @method InvEntrada          setDepositoId()    Sets the current record's "deposito_id" value
 * @method InvEntrada          setNcontrol()      Sets the current record's "ncontrol" value
 * @method InvEntrada          setTasaCambio()    Sets the current record's "tasa_cambio" value
 * @method InvEntrada          setTotal()         Sets the current record's "total" value
 * @method InvEntrada          setAnulado()       Sets the current record's "anulado" value
 * @method InvEntrada          setDescripcion()   Sets the current record's "descripcion" value
 * @method InvEntrada          setEmpresa()       Sets the current record's "Empresa" value
 * @method InvEntrada          setInvDeposito()   Sets the current record's "InvDeposito" value
 * @method InvEntrada          setInvEntradaDet() Sets the current record's "InvEntradaDet" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvEntrada extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inv_entrada');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('deposito_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ncontrol', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 20,
             ));
        $this->hasColumn('tasa_cambio', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('total', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('anulado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('InvDeposito', array(
             'local' => 'deposito_id',
             'foreign' => 'id'));

        $this->hasMany('InvEntradaDet', array(
             'local' => 'id',
             'foreign' => 'inv_entrada_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}