<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Turnover', 'doctrine');

/**
 * BaseTurnover
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $producto_id
 * @property integer $proveedor_id
 * @property string $minimo
 * @property Producto $Producto
 * @property Proveedor $Proveedor
 * 
 * @method integer   getProductoId()   Returns the current record's "producto_id" value
 * @method integer   getProveedorId()  Returns the current record's "proveedor_id" value
 * @method string    getMinimo()       Returns the current record's "minimo" value
 * @method Producto  getProducto()     Returns the current record's "Producto" value
 * @method Proveedor getProveedor()    Returns the current record's "Proveedor" value
 * @method Turnover  setProductoId()   Sets the current record's "producto_id" value
 * @method Turnover  setProveedorId()  Sets the current record's "proveedor_id" value
 * @method Turnover  setMinimo()       Sets the current record's "minimo" value
 * @method Turnover  setProducto()     Sets the current record's "Producto" value
 * @method Turnover  setProveedor()    Sets the current record's "Proveedor" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTurnover extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('turnover');
        $this->hasColumn('producto_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('proveedor_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('minimo', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Proveedor', array(
             'local' => 'proveedor_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}