<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OrdenCompra', 'doctrine');

/**
 * BaseOrdenCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $ncontrol
 * @property string $tasa_cambio
 * @property integer $empresa_id
 * @property integer $deposito_id
 * @property integer $cliente_id
 * @property integer $orden_compra_estatus_id
 * @property string $titulo
 * @property string $total
 * @property Cliente $Cliente
 * @property Empresa $Empresa
 * @property InvDeposito $InvDeposito
 * @property Doctrine_Collection $OrdenCompraDet
 * @property OrdenCompraEstatus $OrdenCompraEstatus
 * @property Doctrine_Collection $Factura
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method string              getNcontrol()                Returns the current record's "ncontrol" value
 * @method string              getTasaCambio()              Returns the current record's "tasa_cambio" value
 * @method integer             getEmpresaId()               Returns the current record's "empresa_id" value
 * @method integer             getDepositoId()              Returns the current record's "deposito_id" value
 * @method integer             getClienteId()               Returns the current record's "cliente_id" value
 * @method integer             getOrdenCompraEstatusId()    Returns the current record's "orden_compra_estatus_id" value
 * @method string              getTitulo()                  Returns the current record's "titulo" value
 * @method string              getTotal()                   Returns the current record's "total" value
 * @method Cliente             getCliente()                 Returns the current record's "Cliente" value
 * @method Empresa             getEmpresa()                 Returns the current record's "Empresa" value
 * @method InvDeposito         getInvDeposito()             Returns the current record's "InvDeposito" value
 * @method Doctrine_Collection getOrdenCompraDet()          Returns the current record's "OrdenCompraDet" collection
 * @method OrdenCompraEstatus  getOrdenCompraEstatus()      Returns the current record's "OrdenCompraEstatus" value
 * @method Doctrine_Collection getFactura()                 Returns the current record's "Factura" collection
 * @method OrdenCompra         setId()                      Sets the current record's "id" value
 * @method OrdenCompra         setNcontrol()                Sets the current record's "ncontrol" value
 * @method OrdenCompra         setTasaCambio()              Sets the current record's "tasa_cambio" value
 * @method OrdenCompra         setEmpresaId()               Sets the current record's "empresa_id" value
 * @method OrdenCompra         setDepositoId()              Sets the current record's "deposito_id" value
 * @method OrdenCompra         setClienteId()               Sets the current record's "cliente_id" value
 * @method OrdenCompra         setOrdenCompraEstatusId()    Sets the current record's "orden_compra_estatus_id" value
 * @method OrdenCompra         setTitulo()                  Sets the current record's "titulo" value
 * @method OrdenCompra         setTotal()                   Sets the current record's "total" value
 * @method OrdenCompra         setCliente()                 Sets the current record's "Cliente" value
 * @method OrdenCompra         setEmpresa()                 Sets the current record's "Empresa" value
 * @method OrdenCompra         setInvDeposito()             Sets the current record's "InvDeposito" value
 * @method OrdenCompra         setOrdenCompraDet()          Sets the current record's "OrdenCompraDet" collection
 * @method OrdenCompra         setOrdenCompraEstatus()      Sets the current record's "OrdenCompraEstatus" value
 * @method OrdenCompra         setFactura()                 Sets the current record's "Factura" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdenCompra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orden_compra');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('ncontrol', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 20,
             ));
        $this->hasColumn('tasa_cambio', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('deposito_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cliente_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('orden_compra_estatus_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('titulo', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('total', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cliente', array(
             'local' => 'cliente_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('InvDeposito', array(
             'local' => 'deposito_id',
             'foreign' => 'id'));

        $this->hasMany('OrdenCompraDet', array(
             'local' => 'id',
             'foreign' => 'orden_compra_id'));

        $this->hasOne('OrdenCompraEstatus', array(
             'local' => 'orden_compra_estatus_id',
             'foreign' => 'id'));

        $this->hasMany('Factura', array(
             'local' => 'id',
             'foreign' => 'orden_compra_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}