<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DevolverCompraDet', 'doctrine');

/**
 * BaseDevolverCompraDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $devolver_compra_id
 * @property string $qty
 * @property string $price_unit
 * @property string $price_tot
 * @property integer $inventario_id
 * @property string $exento
 * @property DevolverCompra $DevolverCompra
 * @property Inventario $Inventario
 * 
 * @method integer           getId()                 Returns the current record's "id" value
 * @method integer           getDevolverCompraId()   Returns the current record's "devolver_compra_id" value
 * @method string            getQty()                Returns the current record's "qty" value
 * @method string            getPriceUnit()          Returns the current record's "price_unit" value
 * @method string            getPriceTot()           Returns the current record's "price_tot" value
 * @method integer           getInventarioId()       Returns the current record's "inventario_id" value
 * @method string            getExento()             Returns the current record's "exento" value
 * @method DevolverCompra    getDevolverCompra()     Returns the current record's "DevolverCompra" value
 * @method Inventario        getInventario()         Returns the current record's "Inventario" value
 * @method DevolverCompraDet setId()                 Sets the current record's "id" value
 * @method DevolverCompraDet setDevolverCompraId()   Sets the current record's "devolver_compra_id" value
 * @method DevolverCompraDet setQty()                Sets the current record's "qty" value
 * @method DevolverCompraDet setPriceUnit()          Sets the current record's "price_unit" value
 * @method DevolverCompraDet setPriceTot()           Sets the current record's "price_tot" value
 * @method DevolverCompraDet setInventarioId()       Sets the current record's "inventario_id" value
 * @method DevolverCompraDet setExento()             Sets the current record's "exento" value
 * @method DevolverCompraDet setDevolverCompra()     Sets the current record's "DevolverCompra" value
 * @method DevolverCompraDet setInventario()         Sets the current record's "Inventario" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDevolverCompraDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('devolver_compra_det');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('devolver_compra_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('qty', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 1,
             'length' => 20,
             ));
        $this->hasColumn('price_unit', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('price_tot', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('inventario_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('exento', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DevolverCompra', array(
             'local' => 'devolver_compra_id',
             'foreign' => 'id'));

        $this->hasOne('Inventario', array(
             'local' => 'inventario_id',
             'foreign' => 'id'));
    }
}