<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OfertaDet', 'doctrine');

/**
 * BaseOfertaDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $oferta_id
 * @property integer $inventario_id
 * @property Oferta $Oferta
 * @property Inventario $Inventario
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method integer    getOfertaId()      Returns the current record's "oferta_id" value
 * @method integer    getInventarioId()  Returns the current record's "inventario_id" value
 * @method Oferta     getOferta()        Returns the current record's "Oferta" value
 * @method Inventario getInventario()    Returns the current record's "Inventario" value
 * @method OfertaDet  setId()            Sets the current record's "id" value
 * @method OfertaDet  setOfertaId()      Sets the current record's "oferta_id" value
 * @method OfertaDet  setInventarioId()  Sets the current record's "inventario_id" value
 * @method OfertaDet  setOferta()        Sets the current record's "Oferta" value
 * @method OfertaDet  setInventario()    Sets the current record's "Inventario" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOfertaDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('oferta_det');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('oferta_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('inventario_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Oferta', array(
             'local' => 'oferta_id',
             'foreign' => 'id'));

        $this->hasOne('Inventario', array(
             'local' => 'inventario_id',
             'foreign' => 'id'));
    }
}