<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cliente', 'doctrine');

/**
 * BaseCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property string $full_name
 * @property string $doc_id
 * @property string $sicm
 * @property string $zona
 * @property string $direccion
 * @property string $telf
 * @property string $celular
 * @property string $email
 * @property tinyint $tipo_precio
 * @property integer $dias_credito
 * @property boolean $activo
 * @property string $descripcion
 * @property integer $vendedor_01
 * @property string $vendedor_01_profit
 * @property integer $vendedor_02
 * @property string $vendedor_02_profit
 * @property Empresa $Empresa
 * @property Doctrine_Collection $Factura
 * @property Doctrine_Collection $NotaEntrega
 * @property Doctrine_Collection $ReciboPago
 * @property Doctrine_Collection $Retenciones
 * @property Doctrine_Collection $NotaCredito
 * @property sfGuardUser $User
 * @property sfGuardUser $User2
 * @property Doctrine_Collection $sfGuardUser
 * @property Doctrine_Collection $ProdVendidos
 * @property Doctrine_Collection $ProdComprados
 * @property Doctrine_Collection $CuentasCobrar
 * @property Doctrine_Collection $AlmacenTransito
 * @property Doctrine_Collection $OrdenCompra
 * @property Doctrine_Collection $Devolver
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getEmpresaId()          Returns the current record's "empresa_id" value
 * @method string              getFullName()           Returns the current record's "full_name" value
 * @method string              getDocId()              Returns the current record's "doc_id" value
 * @method string              getSicm()               Returns the current record's "sicm" value
 * @method string              getZona()               Returns the current record's "zona" value
 * @method string              getDireccion()          Returns the current record's "direccion" value
 * @method string              getTelf()               Returns the current record's "telf" value
 * @method string              getCelular()            Returns the current record's "celular" value
 * @method string              getEmail()              Returns the current record's "email" value
 * @method tinyint             getTipoPrecio()         Returns the current record's "tipo_precio" value
 * @method integer             getDiasCredito()        Returns the current record's "dias_credito" value
 * @method boolean             getActivo()             Returns the current record's "activo" value
 * @method string              getDescripcion()        Returns the current record's "descripcion" value
 * @method integer             getVendedor01()         Returns the current record's "vendedor_01" value
 * @method string              getVendedor01Profit()   Returns the current record's "vendedor_01_profit" value
 * @method integer             getVendedor02()         Returns the current record's "vendedor_02" value
 * @method string              getVendedor02Profit()   Returns the current record's "vendedor_02_profit" value
 * @method Empresa             getEmpresa()            Returns the current record's "Empresa" value
 * @method Doctrine_Collection getFactura()            Returns the current record's "Factura" collection
 * @method Doctrine_Collection getNotaEntrega()        Returns the current record's "NotaEntrega" collection
 * @method Doctrine_Collection getReciboPago()         Returns the current record's "ReciboPago" collection
 * @method Doctrine_Collection getRetenciones()        Returns the current record's "Retenciones" collection
 * @method Doctrine_Collection getNotaCredito()        Returns the current record's "NotaCredito" collection
 * @method sfGuardUser         getUser()               Returns the current record's "User" value
 * @method sfGuardUser         getUser2()              Returns the current record's "User2" value
 * @method Doctrine_Collection getSfGuardUser()        Returns the current record's "sfGuardUser" collection
 * @method Doctrine_Collection getProdVendidos()       Returns the current record's "ProdVendidos" collection
 * @method Doctrine_Collection getProdComprados()      Returns the current record's "ProdComprados" collection
 * @method Doctrine_Collection getCuentasCobrar()      Returns the current record's "CuentasCobrar" collection
 * @method Doctrine_Collection getAlmacenTransito()    Returns the current record's "AlmacenTransito" collection
 * @method Doctrine_Collection getOrdenCompra()        Returns the current record's "OrdenCompra" collection
 * @method Doctrine_Collection getDevolver()           Returns the current record's "Devolver" collection
 * @method Cliente             setId()                 Sets the current record's "id" value
 * @method Cliente             setEmpresaId()          Sets the current record's "empresa_id" value
 * @method Cliente             setFullName()           Sets the current record's "full_name" value
 * @method Cliente             setDocId()              Sets the current record's "doc_id" value
 * @method Cliente             setSicm()               Sets the current record's "sicm" value
 * @method Cliente             setZona()               Sets the current record's "zona" value
 * @method Cliente             setDireccion()          Sets the current record's "direccion" value
 * @method Cliente             setTelf()               Sets the current record's "telf" value
 * @method Cliente             setCelular()            Sets the current record's "celular" value
 * @method Cliente             setEmail()              Sets the current record's "email" value
 * @method Cliente             setTipoPrecio()         Sets the current record's "tipo_precio" value
 * @method Cliente             setDiasCredito()        Sets the current record's "dias_credito" value
 * @method Cliente             setActivo()             Sets the current record's "activo" value
 * @method Cliente             setDescripcion()        Sets the current record's "descripcion" value
 * @method Cliente             setVendedor01()         Sets the current record's "vendedor_01" value
 * @method Cliente             setVendedor01Profit()   Sets the current record's "vendedor_01_profit" value
 * @method Cliente             setVendedor02()         Sets the current record's "vendedor_02" value
 * @method Cliente             setVendedor02Profit()   Sets the current record's "vendedor_02_profit" value
 * @method Cliente             setEmpresa()            Sets the current record's "Empresa" value
 * @method Cliente             setFactura()            Sets the current record's "Factura" collection
 * @method Cliente             setNotaEntrega()        Sets the current record's "NotaEntrega" collection
 * @method Cliente             setReciboPago()         Sets the current record's "ReciboPago" collection
 * @method Cliente             setRetenciones()        Sets the current record's "Retenciones" collection
 * @method Cliente             setNotaCredito()        Sets the current record's "NotaCredito" collection
 * @method Cliente             setUser()               Sets the current record's "User" value
 * @method Cliente             setUser2()              Sets the current record's "User2" value
 * @method Cliente             setSfGuardUser()        Sets the current record's "sfGuardUser" collection
 * @method Cliente             setProdVendidos()       Sets the current record's "ProdVendidos" collection
 * @method Cliente             setProdComprados()      Sets the current record's "ProdComprados" collection
 * @method Cliente             setCuentasCobrar()      Sets the current record's "CuentasCobrar" collection
 * @method Cliente             setAlmacenTransito()    Sets the current record's "AlmacenTransito" collection
 * @method Cliente             setOrdenCompra()        Sets the current record's "OrdenCompra" collection
 * @method Cliente             setDevolver()           Sets the current record's "Devolver" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cliente');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('full_name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('doc_id', 'string', 20, array(
             'type' => 'string',
             'unique' => false,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('sicm', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('zona', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('telf', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('celular', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('tipo_precio', 'tinyint', null, array(
             'type' => 'tinyint',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('dias_credito', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('vendedor_01', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('vendedor_01_profit', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('vendedor_02', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('vendedor_02_profit', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasMany('Factura', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('NotaEntrega', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('ReciboPago', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('Retenciones', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('NotaCredito', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'vendedor_01',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User2', array(
             'local' => 'vendedor_02',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('sfGuardUser', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('ProdVendidos', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('ProdComprados', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('CuentasCobrar', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('AlmacenTransito', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('OrdenCompra', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('Devolver', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}