<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NotaCreditoDet', 'doctrine');

/**
 * BaseNotaCreditoDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nota_credito_id
 * @property integer $cuentas_cobrar_id
 * @property string $monto
 * @property string $descripcion
 * @property boolean $anulado
 * @property NotaCredito $NotaCredito
 * @property CuentasCobrar $CuentasCobrar
 * 
 * @method integer        getId()                Returns the current record's "id" value
 * @method integer        getNotaCreditoId()     Returns the current record's "nota_credito_id" value
 * @method integer        getCuentasCobrarId()   Returns the current record's "cuentas_cobrar_id" value
 * @method string         getMonto()             Returns the current record's "monto" value
 * @method string         getDescripcion()       Returns the current record's "descripcion" value
 * @method boolean        getAnulado()           Returns the current record's "anulado" value
 * @method NotaCredito    getNotaCredito()       Returns the current record's "NotaCredito" value
 * @method CuentasCobrar  getCuentasCobrar()     Returns the current record's "CuentasCobrar" value
 * @method NotaCreditoDet setId()                Sets the current record's "id" value
 * @method NotaCreditoDet setNotaCreditoId()     Sets the current record's "nota_credito_id" value
 * @method NotaCreditoDet setCuentasCobrarId()   Sets the current record's "cuentas_cobrar_id" value
 * @method NotaCreditoDet setMonto()             Sets the current record's "monto" value
 * @method NotaCreditoDet setDescripcion()       Sets the current record's "descripcion" value
 * @method NotaCreditoDet setAnulado()           Sets the current record's "anulado" value
 * @method NotaCreditoDet setNotaCredito()       Sets the current record's "NotaCredito" value
 * @method NotaCreditoDet setCuentasCobrar()     Sets the current record's "CuentasCobrar" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotaCreditoDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nota_credito_det');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nota_credito_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cuentas_cobrar_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('monto', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('anulado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NotaCredito', array(
             'local' => 'nota_credito_id',
             'foreign' => 'id'));

        $this->hasOne('CuentasCobrar', array(
             'local' => 'cuentas_cobrar_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}