<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Galeria', 'doctrine');

/**
 * BaseGaleria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $posicion
 * @property string $texto
 * @property integer $orden
 * @property string $enlace
 * @property string $url_imagen
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getNombre()     Returns the current record's "nombre" value
 * @method string  getPosicion()   Returns the current record's "posicion" value
 * @method string  getTexto()      Returns the current record's "texto" value
 * @method integer getOrden()      Returns the current record's "orden" value
 * @method string  getEnlace()     Returns the current record's "enlace" value
 * @method string  getUrlImagen()  Returns the current record's "url_imagen" value
 * @method Galeria setId()         Sets the current record's "id" value
 * @method Galeria setNombre()     Sets the current record's "nombre" value
 * @method Galeria setPosicion()   Sets the current record's "posicion" value
 * @method Galeria setTexto()      Sets the current record's "texto" value
 * @method Galeria setOrden()      Sets the current record's "orden" value
 * @method Galeria setEnlace()     Sets the current record's "enlace" value
 * @method Galeria setUrlImagen()  Sets the current record's "url_imagen" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGaleria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('galeria');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('posicion', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('texto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('orden', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('enlace', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('url_imagen', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}