<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DevolverCompra', 'doctrine');

/**
 * BaseDevolverCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property string $tasa_cambio
 * @property integer $factura_compra_id
 * @property integer $proveedor_id
 * @property date $fecha
 * @property integer $estatus
 * @property string $descripcion
 * @property Empresa $Empresa
 * @property FacturaCompra $FacturaCompra
 * @property Proveedor $Proveedor
 * @property Doctrine_Collection $DevolverCompraDet
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getEmpresaId()         Returns the current record's "empresa_id" value
 * @method string              getTasaCambio()        Returns the current record's "tasa_cambio" value
 * @method integer             getFacturaCompraId()   Returns the current record's "factura_compra_id" value
 * @method integer             getProveedorId()       Returns the current record's "proveedor_id" value
 * @method date                getFecha()             Returns the current record's "fecha" value
 * @method integer             getEstatus()           Returns the current record's "estatus" value
 * @method string              getDescripcion()       Returns the current record's "descripcion" value
 * @method Empresa             getEmpresa()           Returns the current record's "Empresa" value
 * @method FacturaCompra       getFacturaCompra()     Returns the current record's "FacturaCompra" value
 * @method Proveedor           getProveedor()         Returns the current record's "Proveedor" value
 * @method Doctrine_Collection getDevolverCompraDet() Returns the current record's "DevolverCompraDet" collection
 * @method DevolverCompra      setId()                Sets the current record's "id" value
 * @method DevolverCompra      setEmpresaId()         Sets the current record's "empresa_id" value
 * @method DevolverCompra      setTasaCambio()        Sets the current record's "tasa_cambio" value
 * @method DevolverCompra      setFacturaCompraId()   Sets the current record's "factura_compra_id" value
 * @method DevolverCompra      setProveedorId()       Sets the current record's "proveedor_id" value
 * @method DevolverCompra      setFecha()             Sets the current record's "fecha" value
 * @method DevolverCompra      setEstatus()           Sets the current record's "estatus" value
 * @method DevolverCompra      setDescripcion()       Sets the current record's "descripcion" value
 * @method DevolverCompra      setEmpresa()           Sets the current record's "Empresa" value
 * @method DevolverCompra      setFacturaCompra()     Sets the current record's "FacturaCompra" value
 * @method DevolverCompra      setProveedor()         Sets the current record's "Proveedor" value
 * @method DevolverCompra      setDevolverCompraDet() Sets the current record's "DevolverCompraDet" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDevolverCompra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('devolver_compra');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('tasa_cambio', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('factura_compra_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('proveedor_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('estatus', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('FacturaCompra', array(
             'local' => 'factura_compra_id',
             'foreign' => 'id'));

        $this->hasOne('Proveedor', array(
             'local' => 'proveedor_id',
             'foreign' => 'id'));

        $this->hasMany('DevolverCompraDet', array(
             'local' => 'id',
             'foreign' => 'devolver_compra_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}