<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Carrito', 'doctrine');

/**
 * BaseCarrito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sf_guard_user_id
 * @property integer $inventario_id
 * @property integer $oferta_id
 * @property string $cantidad
 * @property sfGuardUser $User
 * @property Inventario $Inventario
 * @property Oferta $Oferta
 * 
 * @method integer     getId()               Returns the current record's "id" value
 * @method integer     getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method integer     getInventarioId()     Returns the current record's "inventario_id" value
 * @method integer     getOfertaId()         Returns the current record's "oferta_id" value
 * @method string      getCantidad()         Returns the current record's "cantidad" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method Inventario  getInventario()       Returns the current record's "Inventario" value
 * @method Oferta      getOferta()           Returns the current record's "Oferta" value
 * @method Carrito     setId()               Sets the current record's "id" value
 * @method Carrito     setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Carrito     setInventarioId()     Sets the current record's "inventario_id" value
 * @method Carrito     setOfertaId()         Sets the current record's "oferta_id" value
 * @method Carrito     setCantidad()         Sets the current record's "cantidad" value
 * @method Carrito     setUser()             Sets the current record's "User" value
 * @method Carrito     setInventario()       Sets the current record's "Inventario" value
 * @method Carrito     setOferta()           Sets the current record's "Oferta" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarrito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('carrito');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('inventario_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('oferta_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad', 'string', 100, array(
             'type' => 'string',
             'unsigned' => false,
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasOne('Inventario', array(
             'local' => 'inventario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Oferta', array(
             'local' => 'oferta_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}