<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NotaCredito', 'doctrine');

/**
 * BaseNotaCredito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $cliente_id
 * @property string $ncontrol
 * @property tinyint $moneda
 * @property integer $forma_pago_id
 * @property string $num_recibo
 * @property date $fecha
 * @property string $monto
 * @property string $monto_faltante
 * @property string $quien_paga
 * @property string $url_imagen
 * @property string $tasa_cambio
 * @property string $descripcion
 * @property integer $estatus
 * @property FormaPago $FormaPago
 * @property Empresa $Empresa
 * @property Cliente $Cliente
 * @property Doctrine_Collection $NotaCreditoDet
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getEmpresaId()      Returns the current record's "empresa_id" value
 * @method integer             getClienteId()      Returns the current record's "cliente_id" value
 * @method string              getNcontrol()       Returns the current record's "ncontrol" value
 * @method tinyint             getMoneda()         Returns the current record's "moneda" value
 * @method integer             getFormaPagoId()    Returns the current record's "forma_pago_id" value
 * @method string              getNumRecibo()      Returns the current record's "num_recibo" value
 * @method date                getFecha()          Returns the current record's "fecha" value
 * @method string              getMonto()          Returns the current record's "monto" value
 * @method string              getMontoFaltante()  Returns the current record's "monto_faltante" value
 * @method string              getQuienPaga()      Returns the current record's "quien_paga" value
 * @method string              getUrlImagen()      Returns the current record's "url_imagen" value
 * @method string              getTasaCambio()     Returns the current record's "tasa_cambio" value
 * @method string              getDescripcion()    Returns the current record's "descripcion" value
 * @method integer             getEstatus()        Returns the current record's "estatus" value
 * @method FormaPago           getFormaPago()      Returns the current record's "FormaPago" value
 * @method Empresa             getEmpresa()        Returns the current record's "Empresa" value
 * @method Cliente             getCliente()        Returns the current record's "Cliente" value
 * @method Doctrine_Collection getNotaCreditoDet() Returns the current record's "NotaCreditoDet" collection
 * @method NotaCredito         setId()             Sets the current record's "id" value
 * @method NotaCredito         setEmpresaId()      Sets the current record's "empresa_id" value
 * @method NotaCredito         setClienteId()      Sets the current record's "cliente_id" value
 * @method NotaCredito         setNcontrol()       Sets the current record's "ncontrol" value
 * @method NotaCredito         setMoneda()         Sets the current record's "moneda" value
 * @method NotaCredito         setFormaPagoId()    Sets the current record's "forma_pago_id" value
 * @method NotaCredito         setNumRecibo()      Sets the current record's "num_recibo" value
 * @method NotaCredito         setFecha()          Sets the current record's "fecha" value
 * @method NotaCredito         setMonto()          Sets the current record's "monto" value
 * @method NotaCredito         setMontoFaltante()  Sets the current record's "monto_faltante" value
 * @method NotaCredito         setQuienPaga()      Sets the current record's "quien_paga" value
 * @method NotaCredito         setUrlImagen()      Sets the current record's "url_imagen" value
 * @method NotaCredito         setTasaCambio()     Sets the current record's "tasa_cambio" value
 * @method NotaCredito         setDescripcion()    Sets the current record's "descripcion" value
 * @method NotaCredito         setEstatus()        Sets the current record's "estatus" value
 * @method NotaCredito         setFormaPago()      Sets the current record's "FormaPago" value
 * @method NotaCredito         setEmpresa()        Sets the current record's "Empresa" value
 * @method NotaCredito         setCliente()        Sets the current record's "Cliente" value
 * @method NotaCredito         setNotaCreditoDet() Sets the current record's "NotaCreditoDet" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotaCredito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nota_credito');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cliente_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ncontrol', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 20,
             ));
        $this->hasColumn('moneda', 'tinyint', null, array(
             'type' => 'tinyint',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('forma_pago_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('num_recibo', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('monto', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('monto_faltante', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('quien_paga', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('url_imagen', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('tasa_cambio', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('estatus', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FormaPago', array(
             'local' => 'forma_pago_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('Cliente', array(
             'local' => 'cliente_id',
             'foreign' => 'id'));

        $this->hasMany('NotaCreditoDet', array(
             'local' => 'id',
             'foreign' => 'nota_credito_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}