<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('InventarioDet', 'doctrine');

/**
 * BaseInventarioDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $inventario_id
 * @property date $fecha_venc
 * @property string $lote
 * @property string $cantidad
 * @property Inventario $Inventario
 * @property Doctrine_Collection $InvAjusteDet
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getInventarioId()  Returns the current record's "inventario_id" value
 * @method date                getFechaVenc()     Returns the current record's "fecha_venc" value
 * @method string              getLote()          Returns the current record's "lote" value
 * @method string              getCantidad()      Returns the current record's "cantidad" value
 * @method Inventario          getInventario()    Returns the current record's "Inventario" value
 * @method Doctrine_Collection getInvAjusteDet()  Returns the current record's "InvAjusteDet" collection
 * @method InventarioDet       setId()            Sets the current record's "id" value
 * @method InventarioDet       setInventarioId()  Sets the current record's "inventario_id" value
 * @method InventarioDet       setFechaVenc()     Sets the current record's "fecha_venc" value
 * @method InventarioDet       setLote()          Sets the current record's "lote" value
 * @method InventarioDet       setCantidad()      Sets the current record's "cantidad" value
 * @method InventarioDet       setInventario()    Sets the current record's "Inventario" value
 * @method InventarioDet       setInvAjusteDet()  Sets the current record's "InvAjusteDet" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInventarioDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inventario_det');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('inventario_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_venc', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('lote', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('cantidad', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '0',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Inventario', array(
             'local' => 'inventario_id',
             'foreign' => 'id'));

        $this->hasMany('InvAjusteDet', array(
             'local' => 'id',
             'foreign' => 'inventario_det_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}