<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProductoImg', 'doctrine');

/**
 * BaseProductoImg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $producto_id
 * @property string $url_imagen
 * @property string $descripcion
 * @property Producto $Producto
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getProductoId()  Returns the current record's "producto_id" value
 * @method string      getUrlImagen()   Returns the current record's "url_imagen" value
 * @method string      getDescripcion() Returns the current record's "descripcion" value
 * @method Producto    getProducto()    Returns the current record's "Producto" value
 * @method ProductoImg setId()          Sets the current record's "id" value
 * @method ProductoImg setProductoId()  Sets the current record's "producto_id" value
 * @method ProductoImg setUrlImagen()   Sets the current record's "url_imagen" value
 * @method ProductoImg setDescripcion() Sets the current record's "descripcion" value
 * @method ProductoImg setProducto()    Sets the current record's "Producto" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductoImg extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto_img');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('producto_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('url_imagen', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));
    }
}