<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OrdenesCompra', 'doctrine');

/**
 * BaseOrdenesCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $dias_credito
 * @property integer $empresa_id
 * @property integer $proveedor_id
 * @property integer $cotizacion_compra_id
 * @property string $razon_social
 * @property string $doc_id
 * @property string $telf
 * @property string $direccion
 * @property string $ncontrol
 * @property string $tasa_cambio
 * @property string $descuento
 * @property string $subtotal
 * @property string $subtotal_desc
 * @property string $total
 * @property integer $estatus
 * @property Proveedor $Proveedor
 * @property Empresa $Empresa
 * @property Doctrine_Collection $OrdenesCompraDet
 * @property CotizacionCompra $CotizacionCompra
 * @property Doctrine_Collection $FacturaCompra
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getDiasCredito()          Returns the current record's "dias_credito" value
 * @method integer             getEmpresaId()            Returns the current record's "empresa_id" value
 * @method integer             getProveedorId()          Returns the current record's "proveedor_id" value
 * @method integer             getCotizacionCompraId()   Returns the current record's "cotizacion_compra_id" value
 * @method string              getRazonSocial()          Returns the current record's "razon_social" value
 * @method string              getDocId()                Returns the current record's "doc_id" value
 * @method string              getTelf()                 Returns the current record's "telf" value
 * @method string              getDireccion()            Returns the current record's "direccion" value
 * @method string              getNcontrol()             Returns the current record's "ncontrol" value
 * @method string              getTasaCambio()           Returns the current record's "tasa_cambio" value
 * @method string              getDescuento()            Returns the current record's "descuento" value
 * @method string              getSubtotal()             Returns the current record's "subtotal" value
 * @method string              getSubtotalDesc()         Returns the current record's "subtotal_desc" value
 * @method string              getTotal()                Returns the current record's "total" value
 * @method integer             getEstatus()              Returns the current record's "estatus" value
 * @method Proveedor           getProveedor()            Returns the current record's "Proveedor" value
 * @method Empresa             getEmpresa()              Returns the current record's "Empresa" value
 * @method Doctrine_Collection getOrdenesCompraDet()     Returns the current record's "OrdenesCompraDet" collection
 * @method CotizacionCompra    getCotizacionCompra()     Returns the current record's "CotizacionCompra" value
 * @method Doctrine_Collection getFacturaCompra()        Returns the current record's "FacturaCompra" collection
 * @method OrdenesCompra       setId()                   Sets the current record's "id" value
 * @method OrdenesCompra       setDiasCredito()          Sets the current record's "dias_credito" value
 * @method OrdenesCompra       setEmpresaId()            Sets the current record's "empresa_id" value
 * @method OrdenesCompra       setProveedorId()          Sets the current record's "proveedor_id" value
 * @method OrdenesCompra       setCotizacionCompraId()   Sets the current record's "cotizacion_compra_id" value
 * @method OrdenesCompra       setRazonSocial()          Sets the current record's "razon_social" value
 * @method OrdenesCompra       setDocId()                Sets the current record's "doc_id" value
 * @method OrdenesCompra       setTelf()                 Sets the current record's "telf" value
 * @method OrdenesCompra       setDireccion()            Sets the current record's "direccion" value
 * @method OrdenesCompra       setNcontrol()             Sets the current record's "ncontrol" value
 * @method OrdenesCompra       setTasaCambio()           Sets the current record's "tasa_cambio" value
 * @method OrdenesCompra       setDescuento()            Sets the current record's "descuento" value
 * @method OrdenesCompra       setSubtotal()             Sets the current record's "subtotal" value
 * @method OrdenesCompra       setSubtotalDesc()         Sets the current record's "subtotal_desc" value
 * @method OrdenesCompra       setTotal()                Sets the current record's "total" value
 * @method OrdenesCompra       setEstatus()              Sets the current record's "estatus" value
 * @method OrdenesCompra       setProveedor()            Sets the current record's "Proveedor" value
 * @method OrdenesCompra       setEmpresa()              Sets the current record's "Empresa" value
 * @method OrdenesCompra       setOrdenesCompraDet()     Sets the current record's "OrdenesCompraDet" collection
 * @method OrdenesCompra       setCotizacionCompra()     Sets the current record's "CotizacionCompra" value
 * @method OrdenesCompra       setFacturaCompra()        Sets the current record's "FacturaCompra" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdenesCompra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ordenes_compra');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('dias_credito', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('proveedor_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cotizacion_compra_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('razon_social', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('doc_id', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('telf', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('ncontrol', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('tasa_cambio', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('descuento', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 0,
             'length' => 20,
             ));
        $this->hasColumn('subtotal', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('subtotal_desc', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('total', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('estatus', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proveedor', array(
             'local' => 'proveedor_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasMany('OrdenesCompraDet', array(
             'local' => 'id',
             'foreign' => 'ordenes_compra_id'));

        $this->hasOne('CotizacionCompra', array(
             'local' => 'cotizacion_compra_id',
             'foreign' => 'id'));

        $this->hasMany('FacturaCompra', array(
             'local' => 'id',
             'foreign' => 'ordenes_compra_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}