<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Contactenos', 'doctrine');

/**
 * BaseContactenos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property string $nombre
 * @property string $mensaje
 * @property boolean $estatus
 * 
 * @method integer     getId()      Returns the current record's "id" value
 * @method string      getEmail()   Returns the current record's "email" value
 * @method string      getNombre()  Returns the current record's "nombre" value
 * @method string      getMensaje() Returns the current record's "mensaje" value
 * @method boolean     getEstatus() Returns the current record's "estatus" value
 * @method Contactenos setId()      Sets the current record's "id" value
 * @method Contactenos setEmail()   Sets the current record's "email" value
 * @method Contactenos setNombre()  Sets the current record's "nombre" value
 * @method Contactenos setMensaje() Sets the current record's "mensaje" value
 * @method Contactenos setEstatus() Sets the current record's "estatus" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContactenos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactenos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('email', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('mensaje', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('estatus', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}