<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProdCategoria', 'doctrine');

/**
 * BaseProdCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $codigo
 * @property string $codigo_full
 * @property string $nombre
 * @property string $descripcion
 * @property string $url_imagen
 * @property Doctrine_Collection $Producto
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getCodigo()      Returns the current record's "codigo" value
 * @method string              getCodigoFull()  Returns the current record's "codigo_full" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method string              getUrlImagen()   Returns the current record's "url_imagen" value
 * @method Doctrine_Collection getProducto()    Returns the current record's "Producto" collection
 * @method ProdCategoria       setId()          Sets the current record's "id" value
 * @method ProdCategoria       setCodigo()      Sets the current record's "codigo" value
 * @method ProdCategoria       setCodigoFull()  Sets the current record's "codigo_full" value
 * @method ProdCategoria       setNombre()      Sets the current record's "nombre" value
 * @method ProdCategoria       setDescripcion() Sets the current record's "descripcion" value
 * @method ProdCategoria       setUrlImagen()   Sets the current record's "url_imagen" value
 * @method ProdCategoria       setProducto()    Sets the current record's "Producto" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProdCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('prod_categoria');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('codigo_full', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('url_imagen', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Producto', array(
             'local' => 'id',
             'foreign' => 'categoria_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}