<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FacturaCompra', 'doctrine');

/**
 * BaseFacturaCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $fecha
 * @property date $fecha_recepcion
 * @property string $dias_credito
 * @property integer $empresa_id
 * @property integer $deposito_id
 * @property integer $proveedor_id
 * @property integer $ordenes_compra_id
 * @property string $razon_social
 * @property string $doc_id
 * @property string $telf
 * @property string $direccion
 * @property string $ncontrol
 * @property string $num_factura
 * @property string $tasa_cambio
 * @property string $descuento
 * @property string $iva
 * @property string $base_imponible
 * @property string $iva_monto
 * @property string $subtotal
 * @property string $subtotal_desc
 * @property string $total
 * @property string $total2
 * @property string $monto_faltante
 * @property string $monto_pagado
 * @property integer $estatus
 * @property integer $estatus_oc
 * @property integer $sumar_inv
 * @property integer $libro_compras
 * @property Proveedor $Proveedor
 * @property Empresa $Empresa
 * @property InvDeposito $InvDeposito
 * @property Doctrine_Collection $FacturaCompraDet
 * @property Doctrine_Collection $CuentasPagar
 * @property OrdenesCompra $OrdenesCompra
 * @property Doctrine_Collection $DevolverCompra
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method date                getFecha()             Returns the current record's "fecha" value
 * @method date                getFechaRecepcion()    Returns the current record's "fecha_recepcion" value
 * @method string              getDiasCredito()       Returns the current record's "dias_credito" value
 * @method integer             getEmpresaId()         Returns the current record's "empresa_id" value
 * @method integer             getDepositoId()        Returns the current record's "deposito_id" value
 * @method integer             getProveedorId()       Returns the current record's "proveedor_id" value
 * @method integer             getOrdenesCompraId()   Returns the current record's "ordenes_compra_id" value
 * @method string              getRazonSocial()       Returns the current record's "razon_social" value
 * @method string              getDocId()             Returns the current record's "doc_id" value
 * @method string              getTelf()              Returns the current record's "telf" value
 * @method string              getDireccion()         Returns the current record's "direccion" value
 * @method string              getNcontrol()          Returns the current record's "ncontrol" value
 * @method string              getNumFactura()        Returns the current record's "num_factura" value
 * @method string              getTasaCambio()        Returns the current record's "tasa_cambio" value
 * @method string              getDescuento()         Returns the current record's "descuento" value
 * @method string              getIva()               Returns the current record's "iva" value
 * @method string              getBaseImponible()     Returns the current record's "base_imponible" value
 * @method string              getIvaMonto()          Returns the current record's "iva_monto" value
 * @method string              getSubtotal()          Returns the current record's "subtotal" value
 * @method string              getSubtotalDesc()      Returns the current record's "subtotal_desc" value
 * @method string              getTotal()             Returns the current record's "total" value
 * @method string              getTotal2()            Returns the current record's "total2" value
 * @method string              getMontoFaltante()     Returns the current record's "monto_faltante" value
 * @method string              getMontoPagado()       Returns the current record's "monto_pagado" value
 * @method integer             getEstatus()           Returns the current record's "estatus" value
 * @method integer             getEstatusOc()         Returns the current record's "estatus_oc" value
 * @method integer             getSumarInv()          Returns the current record's "sumar_inv" value
 * @method integer             getLibroCompras()      Returns the current record's "libro_compras" value
 * @method Proveedor           getProveedor()         Returns the current record's "Proveedor" value
 * @method Empresa             getEmpresa()           Returns the current record's "Empresa" value
 * @method InvDeposito         getInvDeposito()       Returns the current record's "InvDeposito" value
 * @method Doctrine_Collection getFacturaCompraDet()  Returns the current record's "FacturaCompraDet" collection
 * @method Doctrine_Collection getCuentasPagar()      Returns the current record's "CuentasPagar" collection
 * @method OrdenesCompra       getOrdenesCompra()     Returns the current record's "OrdenesCompra" value
 * @method Doctrine_Collection getDevolverCompra()    Returns the current record's "DevolverCompra" collection
 * @method FacturaCompra       setId()                Sets the current record's "id" value
 * @method FacturaCompra       setFecha()             Sets the current record's "fecha" value
 * @method FacturaCompra       setFechaRecepcion()    Sets the current record's "fecha_recepcion" value
 * @method FacturaCompra       setDiasCredito()       Sets the current record's "dias_credito" value
 * @method FacturaCompra       setEmpresaId()         Sets the current record's "empresa_id" value
 * @method FacturaCompra       setDepositoId()        Sets the current record's "deposito_id" value
 * @method FacturaCompra       setProveedorId()       Sets the current record's "proveedor_id" value
 * @method FacturaCompra       setOrdenesCompraId()   Sets the current record's "ordenes_compra_id" value
 * @method FacturaCompra       setRazonSocial()       Sets the current record's "razon_social" value
 * @method FacturaCompra       setDocId()             Sets the current record's "doc_id" value
 * @method FacturaCompra       setTelf()              Sets the current record's "telf" value
 * @method FacturaCompra       setDireccion()         Sets the current record's "direccion" value
 * @method FacturaCompra       setNcontrol()          Sets the current record's "ncontrol" value
 * @method FacturaCompra       setNumFactura()        Sets the current record's "num_factura" value
 * @method FacturaCompra       setTasaCambio()        Sets the current record's "tasa_cambio" value
 * @method FacturaCompra       setDescuento()         Sets the current record's "descuento" value
 * @method FacturaCompra       setIva()               Sets the current record's "iva" value
 * @method FacturaCompra       setBaseImponible()     Sets the current record's "base_imponible" value
 * @method FacturaCompra       setIvaMonto()          Sets the current record's "iva_monto" value
 * @method FacturaCompra       setSubtotal()          Sets the current record's "subtotal" value
 * @method FacturaCompra       setSubtotalDesc()      Sets the current record's "subtotal_desc" value
 * @method FacturaCompra       setTotal()             Sets the current record's "total" value
 * @method FacturaCompra       setTotal2()            Sets the current record's "total2" value
 * @method FacturaCompra       setMontoFaltante()     Sets the current record's "monto_faltante" value
 * @method FacturaCompra       setMontoPagado()       Sets the current record's "monto_pagado" value
 * @method FacturaCompra       setEstatus()           Sets the current record's "estatus" value
 * @method FacturaCompra       setEstatusOc()         Sets the current record's "estatus_oc" value
 * @method FacturaCompra       setSumarInv()          Sets the current record's "sumar_inv" value
 * @method FacturaCompra       setLibroCompras()      Sets the current record's "libro_compras" value
 * @method FacturaCompra       setProveedor()         Sets the current record's "Proveedor" value
 * @method FacturaCompra       setEmpresa()           Sets the current record's "Empresa" value
 * @method FacturaCompra       setInvDeposito()       Sets the current record's "InvDeposito" value
 * @method FacturaCompra       setFacturaCompraDet()  Sets the current record's "FacturaCompraDet" collection
 * @method FacturaCompra       setCuentasPagar()      Sets the current record's "CuentasPagar" collection
 * @method FacturaCompra       setOrdenesCompra()     Sets the current record's "OrdenesCompra" value
 * @method FacturaCompra       setDevolverCompra()    Sets the current record's "DevolverCompra" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFacturaCompra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('factura_compra');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('fecha_recepcion', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('dias_credito', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('deposito_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('proveedor_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ordenes_compra_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('razon_social', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('doc_id', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('telf', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('ncontrol', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('num_factura', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('tasa_cambio', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('descuento', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 0,
             'length' => 20,
             ));
        $this->hasColumn('iva', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('base_imponible', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('iva_monto', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('subtotal', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('subtotal_desc', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('total', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('total2', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('monto_faltante', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('monto_pagado', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('estatus', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('estatus_oc', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('sumar_inv', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('libro_compras', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proveedor', array(
             'local' => 'proveedor_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('InvDeposito', array(
             'local' => 'deposito_id',
             'foreign' => 'id'));

        $this->hasMany('FacturaCompraDet', array(
             'local' => 'id',
             'foreign' => 'factura_compra_id'));

        $this->hasMany('CuentasPagar', array(
             'local' => 'id',
             'foreign' => 'factura_compra_id'));

        $this->hasOne('OrdenesCompra', array(
             'local' => 'ordenes_compra_id',
             'foreign' => 'id'));

        $this->hasMany('DevolverCompra', array(
             'local' => 'id',
             'foreign' => 'factura_compra_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}