<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FacturaGastosDet', 'doctrine');

/**
 * BaseFacturaGastosDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $factura_gastos_id
 * @property string $qty
 * @property string $price_unit
 * @property string $price_tot
 * @property string $exento
 * @property string $descripcion
 * @property FacturaGastos $FacturaGastos
 * 
 * @method integer          getId()                Returns the current record's "id" value
 * @method integer          getFacturaGastosId()   Returns the current record's "factura_gastos_id" value
 * @method string           getQty()               Returns the current record's "qty" value
 * @method string           getPriceUnit()         Returns the current record's "price_unit" value
 * @method string           getPriceTot()          Returns the current record's "price_tot" value
 * @method string           getExento()            Returns the current record's "exento" value
 * @method string           getDescripcion()       Returns the current record's "descripcion" value
 * @method FacturaGastos    getFacturaGastos()     Returns the current record's "FacturaGastos" value
 * @method FacturaGastosDet setId()                Sets the current record's "id" value
 * @method FacturaGastosDet setFacturaGastosId()   Sets the current record's "factura_gastos_id" value
 * @method FacturaGastosDet setQty()               Sets the current record's "qty" value
 * @method FacturaGastosDet setPriceUnit()         Sets the current record's "price_unit" value
 * @method FacturaGastosDet setPriceTot()          Sets the current record's "price_tot" value
 * @method FacturaGastosDet setExento()            Sets the current record's "exento" value
 * @method FacturaGastosDet setDescripcion()       Sets the current record's "descripcion" value
 * @method FacturaGastosDet setFacturaGastos()     Sets the current record's "FacturaGastos" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFacturaGastosDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('factura_gastos_det');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('factura_gastos_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('qty', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 1,
             'length' => 20,
             ));
        $this->hasColumn('price_unit', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('price_tot', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('exento', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FacturaGastos', array(
             'local' => 'factura_gastos_id',
             'foreign' => 'id'));
    }
}