<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AlmacenTransito', 'doctrine');

/**
 * BaseAlmacenTransito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $deposito_id
 * @property integer $cliente_id
 * @property integer $factura_id
 * @property integer $nota_entrega_id
 * @property integer $traslado_id
 * @property integer $estatus
 * @property string $fecha_embalaje
 * @property string $fecha_despacho
 * @property integer $tipo
 * @property string $boxes
 * @property string $precinto
 * @property string $descripcion
 * @property Empresa $Empresa
 * @property InvDeposito $InvDeposito
 * @property Cliente $Cliente
 * @property Factura $Factura
 * @property NotaEntrega $NotaEntrega
 * @property Traslado $Traslado
 * 
 * @method integer         getId()              Returns the current record's "id" value
 * @method integer         getEmpresaId()       Returns the current record's "empresa_id" value
 * @method integer         getDepositoId()      Returns the current record's "deposito_id" value
 * @method integer         getClienteId()       Returns the current record's "cliente_id" value
 * @method integer         getFacturaId()       Returns the current record's "factura_id" value
 * @method integer         getNotaEntregaId()   Returns the current record's "nota_entrega_id" value
 * @method integer         getTrasladoId()      Returns the current record's "traslado_id" value
 * @method integer         getEstatus()         Returns the current record's "estatus" value
 * @method string          getFechaEmbalaje()   Returns the current record's "fecha_embalaje" value
 * @method string          getFechaDespacho()   Returns the current record's "fecha_despacho" value
 * @method integer         getTipo()            Returns the current record's "tipo" value
 * @method string          getBoxes()           Returns the current record's "boxes" value
 * @method string          getPrecinto()        Returns the current record's "precinto" value
 * @method string          getDescripcion()     Returns the current record's "descripcion" value
 * @method Empresa         getEmpresa()         Returns the current record's "Empresa" value
 * @method InvDeposito     getInvDeposito()     Returns the current record's "InvDeposito" value
 * @method Cliente         getCliente()         Returns the current record's "Cliente" value
 * @method Factura         getFactura()         Returns the current record's "Factura" value
 * @method NotaEntrega     getNotaEntrega()     Returns the current record's "NotaEntrega" value
 * @method Traslado        getTraslado()        Returns the current record's "Traslado" value
 * @method AlmacenTransito setId()              Sets the current record's "id" value
 * @method AlmacenTransito setEmpresaId()       Sets the current record's "empresa_id" value
 * @method AlmacenTransito setDepositoId()      Sets the current record's "deposito_id" value
 * @method AlmacenTransito setClienteId()       Sets the current record's "cliente_id" value
 * @method AlmacenTransito setFacturaId()       Sets the current record's "factura_id" value
 * @method AlmacenTransito setNotaEntregaId()   Sets the current record's "nota_entrega_id" value
 * @method AlmacenTransito setTrasladoId()      Sets the current record's "traslado_id" value
 * @method AlmacenTransito setEstatus()         Sets the current record's "estatus" value
 * @method AlmacenTransito setFechaEmbalaje()   Sets the current record's "fecha_embalaje" value
 * @method AlmacenTransito setFechaDespacho()   Sets the current record's "fecha_despacho" value
 * @method AlmacenTransito setTipo()            Sets the current record's "tipo" value
 * @method AlmacenTransito setBoxes()           Sets the current record's "boxes" value
 * @method AlmacenTransito setPrecinto()        Sets the current record's "precinto" value
 * @method AlmacenTransito setDescripcion()     Sets the current record's "descripcion" value
 * @method AlmacenTransito setEmpresa()         Sets the current record's "Empresa" value
 * @method AlmacenTransito setInvDeposito()     Sets the current record's "InvDeposito" value
 * @method AlmacenTransito setCliente()         Sets the current record's "Cliente" value
 * @method AlmacenTransito setFactura()         Sets the current record's "Factura" value
 * @method AlmacenTransito setNotaEntrega()     Sets the current record's "NotaEntrega" value
 * @method AlmacenTransito setTraslado()        Sets the current record's "Traslado" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlmacenTransito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('almacen_transito');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('deposito_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cliente_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('factura_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('nota_entrega_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('traslado_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('estatus', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('fecha_embalaje', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('fecha_despacho', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('tipo', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('boxes', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('precinto', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('InvDeposito', array(
             'local' => 'deposito_id',
             'foreign' => 'id'));

        $this->hasOne('Cliente', array(
             'local' => 'cliente_id',
             'foreign' => 'id'));

        $this->hasOne('Factura', array(
             'local' => 'factura_id',
             'foreign' => 'id'));

        $this->hasOne('NotaEntrega', array(
             'local' => 'nota_entrega_id',
             'foreign' => 'id'));

        $this->hasOne('Traslado', array(
             'local' => 'traslado_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}