<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Empresa', 'doctrine');

/**
 * BaseEmpresa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $acronimo
 * @property string $ncontrol
 * @property string $nfactura
 * @property string $ndespacho
 * @property string $nentrega
 * @property string $npago
 * @property string $ncredito
 * @property string $ntraslado
 * @property string $ncompra
 * @property string $factcompra
 * @property string $factgasto
 * @property string $ordencompra
 * @property string $coticompra
 * @property string $rif
 * @property string $cod_coorpotulipa
 * @property string $direccion
 * @property string $telefono
 * @property string $email
 * @property tinyint $tipo
 * @property integer $iva
 * @property string $tasa
 * @property date $venc_registro_comercio
 * @property date $venc_rif
 * @property date $venc_bomberos
 * @property date $venc_lic_funcionamiento
 * @property date $venc_uso_conforme
 * @property date $venc_permiso_sanitario
 * @property date $venc_permiso_instalacion
 * @property date $venc_destinado_afines
 * @property date $venc_destinado_abastos
 * @property string $descripcion
 * @property Doctrine_Collection $Oferta
 * @property Doctrine_Collection $Inventario
 * @property Doctrine_Collection $InvDeposito
 * @property Doctrine_Collection $Cliente
 * @property Doctrine_Collection $Factura
 * @property Doctrine_Collection $NotaEntrega
 * @property Doctrine_Collection $User
 * @property Doctrine_Collection $ReciboPago
 * @property Doctrine_Collection $Retenciones
 * @property Doctrine_Collection $NotaCredito
 * @property Doctrine_Collection $Otros
 * @property Doctrine_Collection $ServerConf
 * @property Doctrine_Collection $Traslado
 * @property Doctrine_Collection $EmpresaUser
 * @property Doctrine_Collection $Kardex
 * @property Doctrine_Collection $ProdVendidos
 * @property Doctrine_Collection $ProdComprados
 * @property Doctrine_Collection $CuentasCobrar
 * @property Doctrine_Collection $InvAjuste
 * @property Doctrine_Collection $InvEntrada
 * @property Doctrine_Collection $InvSalida
 * @property Doctrine_Collection $AlmacenTransito
 * @property Doctrine_Collection $OrdenCompra
 * @property Doctrine_Collection $Caja
 * @property Doctrine_Collection $Devolver
 * @property Doctrine_Collection $FacturaCompra
 * @property Doctrine_Collection $FacturaGastos
 * @property Doctrine_Collection $OrdenesCompra
 * @property Doctrine_Collection $CotizacionCompra
 * @property Doctrine_Collection $CuentasPagar
 * @property Doctrine_Collection $ReciboPagoCompra
 * @property Doctrine_Collection $NotaDebito
 * @property Doctrine_Collection $DevolverCompra
 * @property Doctrine_Collection $Banco
 * @property Doctrine_Collection $SafetyStockFarmacia
 * @property Doctrine_Collection $SafetyStockFarmaciaConfig
 * 
 * @method integer             getId()                        Returns the current record's "id" value
 * @method string              getNombre()                    Returns the current record's "nombre" value
 * @method string              getAcronimo()                  Returns the current record's "acronimo" value
 * @method string              getNcontrol()                  Returns the current record's "ncontrol" value
 * @method string              getNfactura()                  Returns the current record's "nfactura" value
 * @method string              getNdespacho()                 Returns the current record's "ndespacho" value
 * @method string              getNentrega()                  Returns the current record's "nentrega" value
 * @method string              getNpago()                     Returns the current record's "npago" value
 * @method string              getNcredito()                  Returns the current record's "ncredito" value
 * @method string              getNtraslado()                 Returns the current record's "ntraslado" value
 * @method string              getNcompra()                   Returns the current record's "ncompra" value
 * @method string              getFactcompra()                Returns the current record's "factcompra" value
 * @method string              getFactgasto()                 Returns the current record's "factgasto" value
 * @method string              getOrdencompra()               Returns the current record's "ordencompra" value
 * @method string              getCoticompra()                Returns the current record's "coticompra" value
 * @method string              getRif()                       Returns the current record's "rif" value
 * @method string              getCodCoorpotulipa()           Returns the current record's "cod_coorpotulipa" value
 * @method string              getDireccion()                 Returns the current record's "direccion" value
 * @method string              getTelefono()                  Returns the current record's "telefono" value
 * @method string              getEmail()                     Returns the current record's "email" value
 * @method tinyint             getTipo()                      Returns the current record's "tipo" value
 * @method integer             getIva()                       Returns the current record's "iva" value
 * @method string              getTasa()                      Returns the current record's "tasa" value
 * @method date                getVencRegistroComercio()      Returns the current record's "venc_registro_comercio" value
 * @method date                getVencRif()                   Returns the current record's "venc_rif" value
 * @method date                getVencBomberos()              Returns the current record's "venc_bomberos" value
 * @method date                getVencLicFuncionamiento()     Returns the current record's "venc_lic_funcionamiento" value
 * @method date                getVencUsoConforme()           Returns the current record's "venc_uso_conforme" value
 * @method date                getVencPermisoSanitario()      Returns the current record's "venc_permiso_sanitario" value
 * @method date                getVencPermisoInstalacion()    Returns the current record's "venc_permiso_instalacion" value
 * @method date                getVencDestinadoAfines()       Returns the current record's "venc_destinado_afines" value
 * @method date                getVencDestinadoAbastos()      Returns the current record's "venc_destinado_abastos" value
 * @method string              getDescripcion()               Returns the current record's "descripcion" value
 * @method Doctrine_Collection getOferta()                    Returns the current record's "Oferta" collection
 * @method Doctrine_Collection getInventario()                Returns the current record's "Inventario" collection
 * @method Doctrine_Collection getInvDeposito()               Returns the current record's "InvDeposito" collection
 * @method Doctrine_Collection getCliente()                   Returns the current record's "Cliente" collection
 * @method Doctrine_Collection getFactura()                   Returns the current record's "Factura" collection
 * @method Doctrine_Collection getNotaEntrega()               Returns the current record's "NotaEntrega" collection
 * @method Doctrine_Collection getUser()                      Returns the current record's "User" collection
 * @method Doctrine_Collection getReciboPago()                Returns the current record's "ReciboPago" collection
 * @method Doctrine_Collection getRetenciones()               Returns the current record's "Retenciones" collection
 * @method Doctrine_Collection getNotaCredito()               Returns the current record's "NotaCredito" collection
 * @method Doctrine_Collection getOtros()                     Returns the current record's "Otros" collection
 * @method Doctrine_Collection getServerConf()                Returns the current record's "ServerConf" collection
 * @method Doctrine_Collection getTraslado()                  Returns the current record's "Traslado" collection
 * @method Doctrine_Collection getEmpresaUser()               Returns the current record's "EmpresaUser" collection
 * @method Doctrine_Collection getKardex()                    Returns the current record's "Kardex" collection
 * @method Doctrine_Collection getProdVendidos()              Returns the current record's "ProdVendidos" collection
 * @method Doctrine_Collection getProdComprados()             Returns the current record's "ProdComprados" collection
 * @method Doctrine_Collection getCuentasCobrar()             Returns the current record's "CuentasCobrar" collection
 * @method Doctrine_Collection getInvAjuste()                 Returns the current record's "InvAjuste" collection
 * @method Doctrine_Collection getInvEntrada()                Returns the current record's "InvEntrada" collection
 * @method Doctrine_Collection getInvSalida()                 Returns the current record's "InvSalida" collection
 * @method Doctrine_Collection getAlmacenTransito()           Returns the current record's "AlmacenTransito" collection
 * @method Doctrine_Collection getOrdenCompra()               Returns the current record's "OrdenCompra" collection
 * @method Doctrine_Collection getCaja()                      Returns the current record's "Caja" collection
 * @method Doctrine_Collection getDevolver()                  Returns the current record's "Devolver" collection
 * @method Doctrine_Collection getFacturaCompra()             Returns the current record's "FacturaCompra" collection
 * @method Doctrine_Collection getFacturaGastos()             Returns the current record's "FacturaGastos" collection
 * @method Doctrine_Collection getOrdenesCompra()             Returns the current record's "OrdenesCompra" collection
 * @method Doctrine_Collection getCotizacionCompra()          Returns the current record's "CotizacionCompra" collection
 * @method Doctrine_Collection getCuentasPagar()              Returns the current record's "CuentasPagar" collection
 * @method Doctrine_Collection getReciboPagoCompra()          Returns the current record's "ReciboPagoCompra" collection
 * @method Doctrine_Collection getNotaDebito()                Returns the current record's "NotaDebito" collection
 * @method Doctrine_Collection getDevolverCompra()            Returns the current record's "DevolverCompra" collection
 * @method Doctrine_Collection getBanco()                     Returns the current record's "Banco" collection
 * @method Doctrine_Collection getSafetyStockFarmacia()       Returns the current record's "SafetyStockFarmacia" collection
 * @method Doctrine_Collection getSafetyStockFarmaciaConfig() Returns the current record's "SafetyStockFarmaciaConfig" collection
 * @method Empresa             setId()                        Sets the current record's "id" value
 * @method Empresa             setNombre()                    Sets the current record's "nombre" value
 * @method Empresa             setAcronimo()                  Sets the current record's "acronimo" value
 * @method Empresa             setNcontrol()                  Sets the current record's "ncontrol" value
 * @method Empresa             setNfactura()                  Sets the current record's "nfactura" value
 * @method Empresa             setNdespacho()                 Sets the current record's "ndespacho" value
 * @method Empresa             setNentrega()                  Sets the current record's "nentrega" value
 * @method Empresa             setNpago()                     Sets the current record's "npago" value
 * @method Empresa             setNcredito()                  Sets the current record's "ncredito" value
 * @method Empresa             setNtraslado()                 Sets the current record's "ntraslado" value
 * @method Empresa             setNcompra()                   Sets the current record's "ncompra" value
 * @method Empresa             setFactcompra()                Sets the current record's "factcompra" value
 * @method Empresa             setFactgasto()                 Sets the current record's "factgasto" value
 * @method Empresa             setOrdencompra()               Sets the current record's "ordencompra" value
 * @method Empresa             setCoticompra()                Sets the current record's "coticompra" value
 * @method Empresa             setRif()                       Sets the current record's "rif" value
 * @method Empresa             setCodCoorpotulipa()           Sets the current record's "cod_coorpotulipa" value
 * @method Empresa             setDireccion()                 Sets the current record's "direccion" value
 * @method Empresa             setTelefono()                  Sets the current record's "telefono" value
 * @method Empresa             setEmail()                     Sets the current record's "email" value
 * @method Empresa             setTipo()                      Sets the current record's "tipo" value
 * @method Empresa             setIva()                       Sets the current record's "iva" value
 * @method Empresa             setTasa()                      Sets the current record's "tasa" value
 * @method Empresa             setVencRegistroComercio()      Sets the current record's "venc_registro_comercio" value
 * @method Empresa             setVencRif()                   Sets the current record's "venc_rif" value
 * @method Empresa             setVencBomberos()              Sets the current record's "venc_bomberos" value
 * @method Empresa             setVencLicFuncionamiento()     Sets the current record's "venc_lic_funcionamiento" value
 * @method Empresa             setVencUsoConforme()           Sets the current record's "venc_uso_conforme" value
 * @method Empresa             setVencPermisoSanitario()      Sets the current record's "venc_permiso_sanitario" value
 * @method Empresa             setVencPermisoInstalacion()    Sets the current record's "venc_permiso_instalacion" value
 * @method Empresa             setVencDestinadoAfines()       Sets the current record's "venc_destinado_afines" value
 * @method Empresa             setVencDestinadoAbastos()      Sets the current record's "venc_destinado_abastos" value
 * @method Empresa             setDescripcion()               Sets the current record's "descripcion" value
 * @method Empresa             setOferta()                    Sets the current record's "Oferta" collection
 * @method Empresa             setInventario()                Sets the current record's "Inventario" collection
 * @method Empresa             setInvDeposito()               Sets the current record's "InvDeposito" collection
 * @method Empresa             setCliente()                   Sets the current record's "Cliente" collection
 * @method Empresa             setFactura()                   Sets the current record's "Factura" collection
 * @method Empresa             setNotaEntrega()               Sets the current record's "NotaEntrega" collection
 * @method Empresa             setUser()                      Sets the current record's "User" collection
 * @method Empresa             setReciboPago()                Sets the current record's "ReciboPago" collection
 * @method Empresa             setRetenciones()               Sets the current record's "Retenciones" collection
 * @method Empresa             setNotaCredito()               Sets the current record's "NotaCredito" collection
 * @method Empresa             setOtros()                     Sets the current record's "Otros" collection
 * @method Empresa             setServerConf()                Sets the current record's "ServerConf" collection
 * @method Empresa             setTraslado()                  Sets the current record's "Traslado" collection
 * @method Empresa             setEmpresaUser()               Sets the current record's "EmpresaUser" collection
 * @method Empresa             setKardex()                    Sets the current record's "Kardex" collection
 * @method Empresa             setProdVendidos()              Sets the current record's "ProdVendidos" collection
 * @method Empresa             setProdComprados()             Sets the current record's "ProdComprados" collection
 * @method Empresa             setCuentasCobrar()             Sets the current record's "CuentasCobrar" collection
 * @method Empresa             setInvAjuste()                 Sets the current record's "InvAjuste" collection
 * @method Empresa             setInvEntrada()                Sets the current record's "InvEntrada" collection
 * @method Empresa             setInvSalida()                 Sets the current record's "InvSalida" collection
 * @method Empresa             setAlmacenTransito()           Sets the current record's "AlmacenTransito" collection
 * @method Empresa             setOrdenCompra()               Sets the current record's "OrdenCompra" collection
 * @method Empresa             setCaja()                      Sets the current record's "Caja" collection
 * @method Empresa             setDevolver()                  Sets the current record's "Devolver" collection
 * @method Empresa             setFacturaCompra()             Sets the current record's "FacturaCompra" collection
 * @method Empresa             setFacturaGastos()             Sets the current record's "FacturaGastos" collection
 * @method Empresa             setOrdenesCompra()             Sets the current record's "OrdenesCompra" collection
 * @method Empresa             setCotizacionCompra()          Sets the current record's "CotizacionCompra" collection
 * @method Empresa             setCuentasPagar()              Sets the current record's "CuentasPagar" collection
 * @method Empresa             setReciboPagoCompra()          Sets the current record's "ReciboPagoCompra" collection
 * @method Empresa             setNotaDebito()                Sets the current record's "NotaDebito" collection
 * @method Empresa             setDevolverCompra()            Sets the current record's "DevolverCompra" collection
 * @method Empresa             setBanco()                     Sets the current record's "Banco" collection
 * @method Empresa             setSafetyStockFarmacia()       Sets the current record's "SafetyStockFarmacia" collection
 * @method Empresa             setSafetyStockFarmaciaConfig() Sets the current record's "SafetyStockFarmaciaConfig" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpresa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empresa');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('acronimo', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('ncontrol', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('nfactura', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('ndespacho', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('nentrega', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('npago', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('ncredito', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('ntraslado', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('ncompra', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('factcompra', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('factgasto', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('ordencompra', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('coticompra', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('rif', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('cod_coorpotulipa', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('direccion', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('telefono', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('email', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('tipo', 'tinyint', null, array(
             'type' => 'tinyint',
             'notnull' => true,
             ));
        $this->hasColumn('iva', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('tasa', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'T01',
             'length' => 20,
             ));
        $this->hasColumn('venc_registro_comercio', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('venc_rif', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('venc_bomberos', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('venc_lic_funcionamiento', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('venc_uso_conforme', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('venc_permiso_sanitario', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('venc_permiso_instalacion', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('venc_destinado_afines', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('venc_destinado_abastos', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Oferta', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Inventario', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('InvDeposito', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Cliente', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Factura', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('NotaEntrega', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('sfGuardUser as User', array(
             'refClass' => 'EmpresaUser',
             'local' => 'empresa_id',
             'foreign' => 'user_id'));

        $this->hasMany('ReciboPago', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Retenciones', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('NotaCredito', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Otros', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('ServerConf', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Traslado', array(
             'local' => 'id',
             'foreign' => 'empresa_desde'));

        $this->hasMany('EmpresaUser', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Kardex', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('ProdVendidos', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('ProdComprados', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('CuentasCobrar', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('InvAjuste', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('InvEntrada', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('InvSalida', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('AlmacenTransito', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('OrdenCompra', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Caja', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Devolver', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('FacturaCompra', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('FacturaGastos', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('OrdenesCompra', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('CotizacionCompra', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('CuentasPagar', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('ReciboPagoCompra', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('NotaDebito', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('DevolverCompra', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Banco', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('SafetyStockFarmacia', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('SafetyStockFarmaciaConfig', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}