<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Otros', 'doctrine');

/**
 * BaseOtros
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property string $nombre
 * @property string $valor
 * @property Empresa $Empresa
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getEmpresaId()  Returns the current record's "empresa_id" value
 * @method string  getNombre()     Returns the current record's "nombre" value
 * @method string  getValor()      Returns the current record's "valor" value
 * @method Empresa getEmpresa()    Returns the current record's "Empresa" value
 * @method Otros   setId()         Sets the current record's "id" value
 * @method Otros   setEmpresaId()  Sets the current record's "empresa_id" value
 * @method Otros   setNombre()     Sets the current record's "nombre" value
 * @method Otros   setValor()      Sets the current record's "valor" value
 * @method Otros   setEmpresa()    Sets the current record's "Empresa" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOtros extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('otros');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('valor', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}