<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Oferta', 'doctrine');

/**
 * BaseOferta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property date $fecha
 * @property date $fecha_venc
 * @property integer $empresa_id
 * @property integer $deposito_id
 * @property string $ncontrol
 * @property integer $tipo_oferta
 * @property boolean $activo
 * @property string $precio_usd
 * @property string $qty
 * @property boolean $exento
 * @property string $tasa
 * @property string $url_imagen
 * @property string $url_imagen_desc
 * @property string $descripcion
 * @property Empresa $Empresa
 * @property InvDeposito $InvDeposito
 * @property Doctrine_Collection $NotaEntregaDet
 * @property Doctrine_Collection $FacturaDet
 * @property Doctrine_Collection $OfertaImg
 * @property Doctrine_Collection $OfertaDet
 * @property Doctrine_Collection $Carrito
 * @property Doctrine_Collection $OrdenCompraDet
 * @property Doctrine_Collection $DevolverDet
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method date                getFecha()           Returns the current record's "fecha" value
 * @method date                getFechaVenc()       Returns the current record's "fecha_venc" value
 * @method integer             getEmpresaId()       Returns the current record's "empresa_id" value
 * @method integer             getDepositoId()      Returns the current record's "deposito_id" value
 * @method string              getNcontrol()        Returns the current record's "ncontrol" value
 * @method integer             getTipoOferta()      Returns the current record's "tipo_oferta" value
 * @method boolean             getActivo()          Returns the current record's "activo" value
 * @method string              getPrecioUsd()       Returns the current record's "precio_usd" value
 * @method string              getQty()             Returns the current record's "qty" value
 * @method boolean             getExento()          Returns the current record's "exento" value
 * @method string              getTasa()            Returns the current record's "tasa" value
 * @method string              getUrlImagen()       Returns the current record's "url_imagen" value
 * @method string              getUrlImagenDesc()   Returns the current record's "url_imagen_desc" value
 * @method string              getDescripcion()     Returns the current record's "descripcion" value
 * @method Empresa             getEmpresa()         Returns the current record's "Empresa" value
 * @method InvDeposito         getInvDeposito()     Returns the current record's "InvDeposito" value
 * @method Doctrine_Collection getNotaEntregaDet()  Returns the current record's "NotaEntregaDet" collection
 * @method Doctrine_Collection getFacturaDet()      Returns the current record's "FacturaDet" collection
 * @method Doctrine_Collection getOfertaImg()       Returns the current record's "OfertaImg" collection
 * @method Doctrine_Collection getOfertaDet()       Returns the current record's "OfertaDet" collection
 * @method Doctrine_Collection getCarrito()         Returns the current record's "Carrito" collection
 * @method Doctrine_Collection getOrdenCompraDet()  Returns the current record's "OrdenCompraDet" collection
 * @method Doctrine_Collection getDevolverDet()     Returns the current record's "DevolverDet" collection
 * @method Oferta              setId()              Sets the current record's "id" value
 * @method Oferta              setNombre()          Sets the current record's "nombre" value
 * @method Oferta              setFecha()           Sets the current record's "fecha" value
 * @method Oferta              setFechaVenc()       Sets the current record's "fecha_venc" value
 * @method Oferta              setEmpresaId()       Sets the current record's "empresa_id" value
 * @method Oferta              setDepositoId()      Sets the current record's "deposito_id" value
 * @method Oferta              setNcontrol()        Sets the current record's "ncontrol" value
 * @method Oferta              setTipoOferta()      Sets the current record's "tipo_oferta" value
 * @method Oferta              setActivo()          Sets the current record's "activo" value
 * @method Oferta              setPrecioUsd()       Sets the current record's "precio_usd" value
 * @method Oferta              setQty()             Sets the current record's "qty" value
 * @method Oferta              setExento()          Sets the current record's "exento" value
 * @method Oferta              setTasa()            Sets the current record's "tasa" value
 * @method Oferta              setUrlImagen()       Sets the current record's "url_imagen" value
 * @method Oferta              setUrlImagenDesc()   Sets the current record's "url_imagen_desc" value
 * @method Oferta              setDescripcion()     Sets the current record's "descripcion" value
 * @method Oferta              setEmpresa()         Sets the current record's "Empresa" value
 * @method Oferta              setInvDeposito()     Sets the current record's "InvDeposito" value
 * @method Oferta              setNotaEntregaDet()  Sets the current record's "NotaEntregaDet" collection
 * @method Oferta              setFacturaDet()      Sets the current record's "FacturaDet" collection
 * @method Oferta              setOfertaImg()       Sets the current record's "OfertaImg" collection
 * @method Oferta              setOfertaDet()       Sets the current record's "OfertaDet" collection
 * @method Oferta              setCarrito()         Sets the current record's "Carrito" collection
 * @method Oferta              setOrdenCompraDet()  Sets the current record's "OrdenCompraDet" collection
 * @method Oferta              setDevolverDet()     Sets the current record's "DevolverDet" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOferta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('oferta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('fecha_venc', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('deposito_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ncontrol', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('tipo_oferta', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('precio_usd', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('qty', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('exento', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('tasa', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'T01',
             'length' => 20,
             ));
        $this->hasColumn('url_imagen', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('url_imagen_desc', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('InvDeposito', array(
             'local' => 'deposito_id',
             'foreign' => 'id'));

        $this->hasMany('NotaEntregaDet', array(
             'local' => 'oferta_id',
             'foreign' => 'id'));

        $this->hasMany('FacturaDet', array(
             'local' => 'id',
             'foreign' => 'oferta_id'));

        $this->hasMany('OfertaImg', array(
             'local' => 'id',
             'foreign' => 'oferta_id'));

        $this->hasMany('OfertaDet', array(
             'local' => 'id',
             'foreign' => 'oferta_id'));

        $this->hasMany('Carrito', array(
             'local' => 'id',
             'foreign' => 'oferta_id'));

        $this->hasMany('OrdenCompraDet', array(
             'local' => 'id',
             'foreign' => 'oferta_id'));

        $this->hasMany('DevolverDet', array(
             'local' => 'id',
             'foreign' => 'oferta_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}