<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GastosTipo', 'doctrine');

/**
 * BaseGastosTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $FacturaGastos
 * @property Doctrine_Collection $Banco
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method Doctrine_Collection getFacturaGastos() Returns the current record's "FacturaGastos" collection
 * @method Doctrine_Collection getBanco()         Returns the current record's "Banco" collection
 * @method GastosTipo          setId()            Sets the current record's "id" value
 * @method GastosTipo          setNombre()        Sets the current record's "nombre" value
 * @method GastosTipo          setDescripcion()   Sets the current record's "descripcion" value
 * @method GastosTipo          setFacturaGastos() Sets the current record's "FacturaGastos" collection
 * @method GastosTipo          setBanco()         Sets the current record's "Banco" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGastosTipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gastos_tipo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 200,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FacturaGastos', array(
             'local' => 'id',
             'foreign' => 'gastos_tipo_id'));

        $this->hasMany('Banco', array(
             'local' => 'id',
             'foreign' => 'gastos_tipo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}