<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NivelServicio', 'doctrine');

/**
 * BaseNivelServicio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $porcentaja
 * @property integer $nivel_servicio
 * @property Doctrine_Collection $SafetyStockFarmaciaConfig
 * 
 * @method integer             getId()                        Returns the current record's "id" value
 * @method integer             getPorcentaje()                Returns the current record's "porcentaje" value
 * @method float               getNivelServicio()             Returns the current record's "nivel_servicio" value
 * @method Doctrine_Collection getSafetyStockFarmaciaConfig() Returns the current record's "SafetyStockFarmaciaConfig" collection
 * @method NivelServicio       setId()                        Sets the current record's "id" value
 * @method NivelServicio       setPorcentaje()                Sets the current record's "porcentaje" value
 * @method NivelServicio       setNivelServicio()             Sets the current record's "nivel_servicio" value
 * @method NivelServicio       setSafetyStockFarmaciaConfig() Sets the current record's "SafetyStockFarmaciaConfig" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNivelServicio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nivel_servicio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('porcentaje', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('nivel_servicio', 'float', 4,2, array(
             'type' => 'float',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SafetyStockFarmaciaConfig', array(
             'local' => 'id',
             'foreign' => 'nivel_servicio_id'));
    }
}