<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CajaEfectivo', 'doctrine');

/**
 * BaseCajaEfectivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $caja_id
 * @property integer $sf_guard_user_id
 * @property date $fecha
 * @property tinyint $moneda
 * @property string $billete
 * @property string $cantidad
 * @property string $descripcion
 * @property Caja $Caja
 * 
 * @method integer      getId()               Returns the current record's "id" value
 * @method integer      getCajaId()           Returns the current record's "caja_id" value
 * @method integer      getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method date         getFecha()            Returns the current record's "fecha" value
 * @method tinyint      getMoneda()           Returns the current record's "moneda" value
 * @method string       getBillete()          Returns the current record's "billete" value
 * @method string       getCantidad()         Returns the current record's "cantidad" value
 * @method string       getDescripcion()      Returns the current record's "descripcion" value
 * @method Caja         getCaja()             Returns the current record's "Caja" value
 * @method CajaEfectivo setId()               Sets the current record's "id" value
 * @method CajaEfectivo setCajaId()           Sets the current record's "caja_id" value
 * @method CajaEfectivo setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method CajaEfectivo setFecha()            Sets the current record's "fecha" value
 * @method CajaEfectivo setMoneda()           Sets the current record's "moneda" value
 * @method CajaEfectivo setBillete()          Sets the current record's "billete" value
 * @method CajaEfectivo setCantidad()         Sets the current record's "cantidad" value
 * @method CajaEfectivo setDescripcion()      Sets the current record's "descripcion" value
 * @method CajaEfectivo setCaja()             Sets the current record's "Caja" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCajaEfectivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('caja_efectivo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('caja_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('moneda', 'tinyint', null, array(
             'type' => 'tinyint',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('billete', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('cantidad', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Caja', array(
             'local' => 'caja_id',
             'foreign' => 'id'));
    }
}