<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OrdenCompraEstatus', 'doctrine');

/**
 * BaseOrdenCompraEstatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $OrdenCompra
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method Doctrine_Collection getOrdenCompra() Returns the current record's "OrdenCompra" collection
 * @method OrdenCompraEstatus  setId()          Sets the current record's "id" value
 * @method OrdenCompraEstatus  setNombre()      Sets the current record's "nombre" value
 * @method OrdenCompraEstatus  setOrdenCompra() Sets the current record's "OrdenCompra" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdenCompraEstatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orden_compra_estatus');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OrdenCompra', array(
             'local' => 'id',
             'foreign' => 'orden_compra_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}