<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CajaCorte', 'doctrine');

/**
 * BaseCajaCorte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $caja_id
 * @property integer $sf_guard_user_id
 * @property boolean $tipo
 * @property timestamp $fecha_ini
 * @property timestamp $fecha_fin
 * @property string $ult_repz
 * @property string $fecha_repz
 * @property string $hora_repz
 * @property string $ult_fact
 * @property string $fecha_ult_fact
 * @property string $hora_ult_fact
 * @property string $ult_nc
 * @property string $exento_fact
 * @property string $base_impt1_fact
 * @property string $iva_t1_fact
 * @property string $exento_nc
 * @property string $base_impt1_nc
 * @property string $iva_t1_nc
 * @property string $codigof
 * @property integer $cant_fact
 * @property integer $cant_nc
 * @property Caja $Caja
 * 
 * @method integer   getId()               Returns the current record's "id" value
 * @method integer   getCajaId()           Returns the current record's "caja_id" value
 * @method integer   getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method boolean   getTipo()             Returns the current record's "tipo" value
 * @method timestamp getFechaIni()         Returns the current record's "fecha_ini" value
 * @method timestamp getFechaFin()         Returns the current record's "fecha_fin" value
 * @method string    getUltRepz()          Returns the current record's "ult_repz" value
 * @method string    getFechaRepz()        Returns the current record's "fecha_repz" value
 * @method string    getHoraRepz()         Returns the current record's "hora_repz" value
 * @method string    getUltFact()          Returns the current record's "ult_fact" value
 * @method string    getFechaUltFact()     Returns the current record's "fecha_ult_fact" value
 * @method string    getHoraUltFact()      Returns the current record's "hora_ult_fact" value
 * @method string    getUltNc()            Returns the current record's "ult_nc" value
 * @method string    getExentoFact()       Returns the current record's "exento_fact" value
 * @method string    getBaseImpt1Fact()    Returns the current record's "base_impt1_fact" value
 * @method string    getIvaT1Fact()        Returns the current record's "iva_t1_fact" value
 * @method string    getExentoNc()         Returns the current record's "exento_nc" value
 * @method string    getBaseImpt1Nc()      Returns the current record's "base_impt1_nc" value
 * @method string    getIvaT1Nc()          Returns the current record's "iva_t1_nc" value
 * @method string    getCodigof()          Returns the current record's "codigof" value
 * @method integer   getCantFact()         Returns the current record's "cant_fact" value
 * @method integer   getCantNc()           Returns the current record's "cant_nc" value
 * @method Caja      getCaja()             Returns the current record's "Caja" value
 * @method CajaCorte setId()               Sets the current record's "id" value
 * @method CajaCorte setCajaId()           Sets the current record's "caja_id" value
 * @method CajaCorte setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method CajaCorte setTipo()             Sets the current record's "tipo" value
 * @method CajaCorte setFechaIni()         Sets the current record's "fecha_ini" value
 * @method CajaCorte setFechaFin()         Sets the current record's "fecha_fin" value
 * @method CajaCorte setUltRepz()          Sets the current record's "ult_repz" value
 * @method CajaCorte setFechaRepz()        Sets the current record's "fecha_repz" value
 * @method CajaCorte setHoraRepz()         Sets the current record's "hora_repz" value
 * @method CajaCorte setUltFact()          Sets the current record's "ult_fact" value
 * @method CajaCorte setFechaUltFact()     Sets the current record's "fecha_ult_fact" value
 * @method CajaCorte setHoraUltFact()      Sets the current record's "hora_ult_fact" value
 * @method CajaCorte setUltNc()            Sets the current record's "ult_nc" value
 * @method CajaCorte setExentoFact()       Sets the current record's "exento_fact" value
 * @method CajaCorte setBaseImpt1Fact()    Sets the current record's "base_impt1_fact" value
 * @method CajaCorte setIvaT1Fact()        Sets the current record's "iva_t1_fact" value
 * @method CajaCorte setExentoNc()         Sets the current record's "exento_nc" value
 * @method CajaCorte setBaseImpt1Nc()      Sets the current record's "base_impt1_nc" value
 * @method CajaCorte setIvaT1Nc()          Sets the current record's "iva_t1_nc" value
 * @method CajaCorte setCodigof()          Sets the current record's "codigof" value
 * @method CajaCorte setCantFact()         Sets the current record's "cant_fact" value
 * @method CajaCorte setCantNc()           Sets the current record's "cant_nc" value
 * @method CajaCorte setCaja()             Sets the current record's "Caja" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCajaCorte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('caja_corte');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('caja_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('tipo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('fecha_ini', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_fin', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('ult_repz', 'string', 5, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 5,
             ));
        $this->hasColumn('fecha_repz', 'string', 6, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 6,
             ));
        $this->hasColumn('hora_repz', 'string', 4, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('ult_fact', 'string', 8, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 8,
             ));
        $this->hasColumn('fecha_ult_fact', 'string', 8, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 8,
             ));
        $this->hasColumn('hora_ult_fact', 'string', 4, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('ult_nc', 'string', 8, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 8,
             ));
        $this->hasColumn('exento_fact', 'string', 18, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 18,
             ));
        $this->hasColumn('base_impt1_fact', 'string', 18, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 18,
             ));
        $this->hasColumn('iva_t1_fact', 'string', 18, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 18,
             ));
        $this->hasColumn('exento_nc', 'string', 18, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 18,
             ));
        $this->hasColumn('base_impt1_nc', 'string', 18, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 18,
             ));
        $this->hasColumn('iva_t1_nc', 'string', 18, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 18,
             ));
        $this->hasColumn('codigof', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('cant_fact', 'integer', 3, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 3,
             ));
        $this->hasColumn('cant_nc', 'integer', 3, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Caja', array(
             'local' => 'caja_id',
             'foreign' => 'id'));
    }
}