<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ServerConf', 'doctrine');

/**
 * BaseServerConf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $deposito_id
 * @property Empresa $Empresa
 * @property InvDeposito $InvDeposito
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getEmpresaId()   Returns the current record's "empresa_id" value
 * @method integer     getDepositoId()  Returns the current record's "deposito_id" value
 * @method Empresa     getEmpresa()     Returns the current record's "Empresa" value
 * @method InvDeposito getInvDeposito() Returns the current record's "InvDeposito" value
 * @method ServerConf  setId()          Sets the current record's "id" value
 * @method ServerConf  setEmpresaId()   Sets the current record's "empresa_id" value
 * @method ServerConf  setDepositoId()  Sets the current record's "deposito_id" value
 * @method ServerConf  setEmpresa()     Sets the current record's "Empresa" value
 * @method ServerConf  setInvDeposito() Sets the current record's "InvDeposito" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServerConf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('server_conf');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('deposito_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('InvDeposito', array(
             'local' => 'deposito_id',
             'foreign' => 'id'));
    }
}