<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OrdenCompraDet', 'doctrine');

/**
 * BaseOrdenCompraDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $orden_compra_id
 * @property string $qty
 * @property string $price_unit
 * @property string $price_tot
 * @property integer $inventario_id
 * @property integer $oferta_id
 * @property string $descripcion
 * @property string $exento
 * @property string $tasa_cambio
 * @property Inventario $Inventario
 * @property Oferta $Oferta
 * @property OrdenCompra $OrdenCompra
 * 
 * @method integer        getId()              Returns the current record's "id" value
 * @method integer        getOrdenCompraId()   Returns the current record's "orden_compra_id" value
 * @method string         getQty()             Returns the current record's "qty" value
 * @method string         getPriceUnit()       Returns the current record's "price_unit" value
 * @method string         getPriceTot()        Returns the current record's "price_tot" value
 * @method integer        getInventarioId()    Returns the current record's "inventario_id" value
 * @method integer        getOfertaId()        Returns the current record's "oferta_id" value
 * @method string         getDescripcion()     Returns the current record's "descripcion" value
 * @method string         getExento()          Returns the current record's "exento" value
 * @method string         getTasaCambio()      Returns the current record's "tasa_cambio" value
 * @method Inventario     getInventario()      Returns the current record's "Inventario" value
 * @method Oferta         getOferta()          Returns the current record's "Oferta" value
 * @method OrdenCompra    getOrdenCompra()     Returns the current record's "OrdenCompra" value
 * @method OrdenCompraDet setId()              Sets the current record's "id" value
 * @method OrdenCompraDet setOrdenCompraId()   Sets the current record's "orden_compra_id" value
 * @method OrdenCompraDet setQty()             Sets the current record's "qty" value
 * @method OrdenCompraDet setPriceUnit()       Sets the current record's "price_unit" value
 * @method OrdenCompraDet setPriceTot()        Sets the current record's "price_tot" value
 * @method OrdenCompraDet setInventarioId()    Sets the current record's "inventario_id" value
 * @method OrdenCompraDet setOfertaId()        Sets the current record's "oferta_id" value
 * @method OrdenCompraDet setDescripcion()     Sets the current record's "descripcion" value
 * @method OrdenCompraDet setExento()          Sets the current record's "exento" value
 * @method OrdenCompraDet setTasaCambio()      Sets the current record's "tasa_cambio" value
 * @method OrdenCompraDet setInventario()      Sets the current record's "Inventario" value
 * @method OrdenCompraDet setOferta()          Sets the current record's "Oferta" value
 * @method OrdenCompraDet setOrdenCompra()     Sets the current record's "OrdenCompra" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdenCompraDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orden_compra_det');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('orden_compra_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('qty', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('price_unit', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('price_tot', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('inventario_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('oferta_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('exento', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('tasa_cambio', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Inventario', array(
             'local' => 'inventario_id',
             'foreign' => 'id'));

        $this->hasOne('Oferta', array(
             'local' => 'oferta_id',
             'foreign' => 'id'));

        $this->hasOne('OrdenCompra', array(
             'local' => 'orden_compra_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}