<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('InvSalidaDet', 'doctrine');

/**
 * BaseInvSalidaDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $inv_salida_id
 * @property string $qty
 * @property string $price_unit
 * @property string $price_tot
 * @property integer $inventario_id
 * @property string $devolucion
 * @property InvSalida $InvSalida
 * @property Inventario $Inventario
 * 
 * @method integer      getId()            Returns the current record's "id" value
 * @method integer      getInvSalidaId()   Returns the current record's "inv_salida_id" value
 * @method string       getQty()           Returns the current record's "qty" value
 * @method string       getPriceUnit()     Returns the current record's "price_unit" value
 * @method string       getPriceTot()      Returns the current record's "price_tot" value
 * @method integer      getInventarioId()  Returns the current record's "inventario_id" value
 * @method string       getDevolucion()    Returns the current record's "devolucion" value
 * @method InvSalida    getInvSalida()     Returns the current record's "InvSalida" value
 * @method Inventario   getInventario()    Returns the current record's "Inventario" value
 * @method InvSalidaDet setId()            Sets the current record's "id" value
 * @method InvSalidaDet setInvSalidaId()   Sets the current record's "inv_salida_id" value
 * @method InvSalidaDet setQty()           Sets the current record's "qty" value
 * @method InvSalidaDet setPriceUnit()     Sets the current record's "price_unit" value
 * @method InvSalidaDet setPriceTot()      Sets the current record's "price_tot" value
 * @method InvSalidaDet setInventarioId()  Sets the current record's "inventario_id" value
 * @method InvSalidaDet setDevolucion()    Sets the current record's "devolucion" value
 * @method InvSalidaDet setInvSalida()     Sets the current record's "InvSalida" value
 * @method InvSalidaDet setInventario()    Sets the current record's "Inventario" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvSalidaDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inv_salida_det');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('inv_salida_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('qty', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 1,
             'length' => 20,
             ));
        $this->hasColumn('price_unit', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('price_tot', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('inventario_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('devolucion', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('InvSalida', array(
             'local' => 'inv_salida_id',
             'foreign' => 'id'));

        $this->hasOne('Inventario', array(
             'local' => 'inventario_id',
             'foreign' => 'id'));
    }
}