<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CajaArqueo', 'doctrine');

/**
 * BaseCajaArqueo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $caja_id
 * @property integer $sf_guard_user_id
 * @property date $fecha
 * @property tinyint $moneda
 * @property integer $forma_pago_id
 * @property string $monto
 * @property string $descripcion
 * @property Caja $Caja
 * @property FormaPago $FormaPago
 * 
 * @method integer    getId()               Returns the current record's "id" value
 * @method integer    getCajaId()           Returns the current record's "caja_id" value
 * @method integer    getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method date       getFecha()            Returns the current record's "fecha" value
 * @method tinyint    getMoneda()           Returns the current record's "moneda" value
 * @method integer    getFormaPagoId()      Returns the current record's "forma_pago_id" value
 * @method string     getMonto()            Returns the current record's "monto" value
 * @method string     getDescripcion()      Returns the current record's "descripcion" value
 * @method Caja       getCaja()             Returns the current record's "Caja" value
 * @method FormaPago  getFormaPago()        Returns the current record's "FormaPago" value
 * @method CajaArqueo setId()               Sets the current record's "id" value
 * @method CajaArqueo setCajaId()           Sets the current record's "caja_id" value
 * @method CajaArqueo setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method CajaArqueo setFecha()            Sets the current record's "fecha" value
 * @method CajaArqueo setMoneda()           Sets the current record's "moneda" value
 * @method CajaArqueo setFormaPagoId()      Sets the current record's "forma_pago_id" value
 * @method CajaArqueo setMonto()            Sets the current record's "monto" value
 * @method CajaArqueo setDescripcion()      Sets the current record's "descripcion" value
 * @method CajaArqueo setCaja()             Sets the current record's "Caja" value
 * @method CajaArqueo setFormaPago()        Sets the current record's "FormaPago" value
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCajaArqueo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('caja_arqueo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('caja_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('moneda', 'tinyint', null, array(
             'type' => 'tinyint',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('forma_pago_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('monto', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Caja', array(
             'local' => 'caja_id',
             'foreign' => 'id'));

        $this->hasOne('FormaPago', array(
             'local' => 'forma_pago_id',
             'foreign' => 'id'));
    }
}