# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false
    timeout:                259200
    lifetime:                259200

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_DEPRECATED)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false
    timeout:                259200
    lifetime:                259200

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_DEPRECATED)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false
    timeout:                259200
    lifetime:                259200

all:
  .settings:
    timeout:                259200
    lifetime:                259200
    #errors
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_DEPRECATED)."\n" ?>

    #modules
    enabled_modules:        [default, sfAdminDash, sfGuardAuth, sfGuardGroup, sfGuardUser, sfGuardPermission]

    # Form security secret (CSRF protection)
    csrf_secret:            ee365546a566303868d04ce0b3ea8584176c8856

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure
