<?php

/**
 * AlmacenTransitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlmacenTransitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlmacenTransitoTable
     */
    public static function getInstance()
    {
      return Doctrine_Core::getTable('AlmacenTransito');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, e.nombre as ename, e.acronimo as emin, id.nombre as dname, c.full_name as cname, c.doc_id as docid,
      f.id as fid, f.num_factura as fnum, ne.id as neid, ne.ncontrol as nenum, t.id as tid')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.InvDeposito id')
        ->leftJoin($rootAlias . '.Cliente c')
        ->leftJoin($rootAlias . '.Factura f')
        ->leftJoin($rootAlias . '.NotaEntrega ne')
        ->leftJoin($rootAlias . '.Traslado t');
    }
}