<?php

/**
 * CajaDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CajaDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CajaDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CajaDet');
    }
}