<?php

/**
 * CajaEfectivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CajaEfectivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CajaEfectivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CajaEfectivo');
    }
}