<?php

/**
 * CajaColaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CajaColaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CajaColaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CajaCola');
    }
}