<?php

/**
 * CajaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CajaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CajaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Caja');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, e.nombre as ename')
        ->leftJoin($rootAlias . '.Empresa e');
    }
}