<?php

/**
 * Caja
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Caja extends BaseCaja
{
public function getCompany() {
    return $this["ename"];
  }
  public function getTipoImp() {
    if($this->getTipo()==0) {
      return "TERMICA";
    } else if($this->getTipo()==1){
      return "FISCAL";
    } 
  }
  public function getEstatus() {
    if($this->getStatus()==0) {
      return "Cerrada";
    } else if($this->getStatus()==1){
      return "Abierta";
    } 
  }
  public function getCreatedByUser() {
      $user=Doctrine::getTable('SfGuardUser')->findOneBy('id',$this->getCreatedBy());
      return $user->getFirstName()." ".$user->getLastName()." (".$user->getUsername().")";
  }
  public function getUpdatedByUser() {
      $user=Doctrine::getTable('SfGuardUser')->findOneBy('id',$this->getUpdatedBy());
      return $user->getFirstName()." ".$user->getLastName()." (".$user->getUsername().")";
  }
}