<?php

/**
 * Cliente
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cliente extends BaseCliente
{
  public function  __toString()
  {
      return sprintf('%s', $this->getFullName()." [".$this->getDocId()."]");
  }
  public function getCompany() {
    return $this["emin"];
  }
  public function getEstatusTxt() {
    if($this->getActivo()) {
      return "HABILITADO";
    } else {
      return "DES-HABILITADO";
    }
  }
  public function getTipoDePrecio() {
    switch ($this->getTipoPrecio()) {
    case 1:
      return "PRECIO 01";
      break;
    case 2:
      return "PRECIO 02";
      break;
    case 3:
      return "PRECIO 03";
      break;
    case 4:
      return "PRECIO 04";
      break;
    case 5:
      return "PRECIO 05";
      break;
    case 6:
      return "PRECIO 06";
      break;
    case 7:
      return "PRECIO 07";
      break;
    }
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
}
