<?php

/**
 * ClienteTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cliente');
    }
    public static function doChoices()
    {
      return Doctrine_Query::create()
      ->select('c.full_name, c.doc_id, c.id')
      ->from('Cliente c')
      ->orderBy('c.full_name ASC, c.doc_id ASC')
      ->execute();
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, e.nombre as ename, e.acronimo as emin')
        ->leftJoin($rootAlias . '.Empresa e');
    }
}
