<?php

/**
 * CompuestoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompuestoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompuestoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Compuesto');
    }
}