<?php

/**
 * CotizacionCompraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CotizacionCompraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CotizacionCompraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CotizacionCompra');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, LPAD(ncontrol, 6, 0) as ncontrol, CAST(ncontrol AS UNSIGNED) as ninteger,
      FORMAT(REPLACE(total, " ", ""), 4, "de_DE") as totalf, e.nombre as ename, e.acronimo as emin')
        ->leftJoin($rootAlias . '.Empresa e');
    }
}