<?php

/**
 * CotizacionCompraDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CotizacionCompraDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CotizacionCompraDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CotizacionCompraDet');
    }
}