<?php

/**
 * CuentasCobrarTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CuentasCobrarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CuentasCobrarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CuentasCobrar');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, c.full_name as cname, c.doc_id as docid,
      f.id as fid, f.num_factura as fnum, f.ndespacho as fdespacho, ne.id as neid, ne.ncontrol as nenum, e.id as eid, e.nombre as ename, e.acronimo as emin')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Cliente c')
        ->leftJoin($rootAlias . '.Factura f')
        ->leftJoin($rootAlias . '.NotaEntrega ne');
    }
}
