<?php

/**
 * CuentasPagarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CuentasPagarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CuentasPagarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CuentasPagar');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, p.full_name as pname, p.doc_id as docid,
      fecha as femision, fecha_recepcion as frecepcion,
      
      f.id as fid, f.num_factura as fnum, f.ncontrol as ncontrol,
      FORMAT(REPLACE(f.total2, " ", ""), 4, "de_DE") as total2_txt, f.total2 as ftotal2,
      f.base_imponible as base_imponible, f.subtotal as subtotal, f.subtotal_desc as subtotal_desc,
      f.tasa_cambio as tasa, f.iva as iva, f.iva_monto as ivamonto,
      CAST(f.dias_credito AS UNSIGNED) as diascredito, f.libro_compras as flibro_compras,

      fg.id as fgid, fg.num_factura as fgnum, fg.ncontrol as gncontrol,
      FORMAT(REPLACE(fg.total2, " ", ""), 4, "de_DE") as gtotal2_txt, fg.total2 as gtotal2,
      fg.base_imponible as gbase_imponible, fg.subtotal as gsubtotal, fg.subtotal_desc as gsubtotal_desc,
      fg.tasa_cambio as gtasa, fg.iva as giva, fg.iva_monto as givamonto,
      CAST(fg.dias_credito AS UNSIGNED) as gdiascredito, fg.libro_compras as libro_compras, fg.tipo as tipo,

      FORMAT(REPLACE(total, " ", ""), 4, "de_DE") as total_txt,
      FORMAT(REPLACE(monto_faltante, " ", ""), 4, "de_DE") as monto_faltante_txt,
      FORMAT(REPLACE(monto_pagado, " ", ""), 4, "de_DE") as monto_pagado_txt,

      e.id as eid, e.nombre as ename, e.acronimo as emin')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Proveedor p')
        ->leftJoin($rootAlias . '.FacturaCompra f')
        ->leftJoin($rootAlias . '.FacturaGastos fg');
    }
}