<?php

/**
 * DevolverCompraDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DevolverCompraDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DevolverCompraDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DevolverCompraDet');
    }
}