<?php

/**
 * DevolverCompraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DevolverCompraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DevolverCompraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DevolverCompra');
    }

    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, e.nombre as ename, e.acronimo as emin, f.num_factura as nfactura, p.full_name as pname')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.FacturaCompra f')
        ->leftJoin($rootAlias . '.Proveedor p');
    }    
}