<?php

/**
 * DevolverTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DevolverTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DevolverTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Devolver');
    }
}