<?php

/**
 * DevolverDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DevolverDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DevolverDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DevolverDet');
    }
}