<?php

/**
 * Empresa
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Empresa extends BaseEmpresa
{
  public function  __toString()
  {
      return sprintf('%s', $this->getNombre());
  }
  public function getTipoEmpresa() {
    if($this->getTipo()==1) {
      return "CASA MATRIZ";
    } else if($this->getTipo()==2){
      return "DROGUERIA";
    } else if($this->getTipo()==3){
      return "FARMACIA";
    } else {
      return "ALIMENTOS";
    }
  }
  public function getTipoTasa() {
    if($this->getTasa()=="T01") {
      return "TASA DE MEDICAMENTOS";
    } else if($this->getTasa()=="T02"){
      return "TASA DE MISCELANEOS";
    } else {
      return "AMBAS TASAS";
    }
  }
  public function getNuevoNcontrol() {
    list($prenc,$nc)=explode("-", $this->getNControl());
    $nc+=1;
    if($nc>9999) {
      $nctxt=str_pad($nc, 5, '0', STR_PAD_LEFT);
    } else {
      $nctxt=str_pad($nc, 4, '0', STR_PAD_LEFT);
    }
    return $prenc."-".$nctxt;
  }
  public function getNuevoNFactura() {
    list($prenf,$nf)=explode("-", $this->getNFactura());
    $nf+=1;
    if($nf>9999) {
      $nftxt=str_pad($nf, 5, '0', STR_PAD_LEFT);
    } else {
      $nftxt=str_pad($nf, 4, '0', STR_PAD_LEFT);
    }
    return $prenf."-".$nftxt;
  }

  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
}
