<?php

/**
 * EmpresaUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpresaUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpresaUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmpresaUser');
    }
}