<?php

/**
 * FacturaCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FacturaCompra extends BaseFacturaCompra
{
  public function getCompany() {
    return $this["emin"];
  }
  public function getTotalCoin() {
    return "USD ".number_format(number_float222($this->getTotal()), 4, ',', ' ');
  }
  public function getPendienteCoin() {
    return "USD ".number_format(number_float222($this->getMontoFaltante()), 4, ',', ' ');
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
}

function number_float222($str) {
  $stripped = str_replace(' ', '', $str);
  $number = str_replace(',', '', $stripped);
  return floatval($number);
}
