<?php

/**
 * FacturaCompraDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacturaCompraDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacturaCompraDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FacturaCompraDet');
    }
}