<?php

/**
 * FacturaDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacturaDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacturaDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FacturaDet');
    }
}