<?php

/**
 * FacturaTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Factura');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, e.nombre as ename, e.acronimo as emin')
        ->leftJoin($rootAlias . '.Empresa e');

    }
    public static function doSelectJoinOtros2($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*')
        ->orderBy($rootAlias.'.created_at DESC');
    }
}
