<?php

/**
 * FormaPago
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FormaPago extends BaseFormaPago
{
  public function  __toString()
  {
      return sprintf('%s', $this->getNombre());
  }
  public function getEstatus() {
    if($this->getActivo()==0) {
      return "DES-HABILITADO";
    } else {
      return "HABILITADO";
    }
  }
  public function getCoin() {
    if($this->getMoneda()==1) {
      return "BOLIVARES";
    } else if($this->getMoneda()==2) {
      return "DOLARES";
    }
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
}
