<?php

/**
 * FormaPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormaPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormaPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormaPago');
    }
}