<?php

/**
 * GaleriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GaleriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GaleriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Galeria');
    }
}