<?php

/**
 * InexistenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InexistenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InexistenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Inexistencia');
    }
}