<?php

/**
 * InvAjuste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class InvAjuste extends BaseInvAjuste
{
    public function getTipoOper() {
      if($this["tipo"]==1) {
        return "ENTRADA DE INV.";
      } else {
        return "SALIDA DE INV.";
      }
    }
    public function getEmpresaName() {
      return $this["ename"];
    }
    public function getCompany() {
      return $this["emin"];
    }
    public function getDepositoName() {
      return $this["idname"];
    }
    public function getCreatedByUser() {
      $user=Doctrine::getTable('SfGuardUser')->findOneBy('id',$this->getCreatedBy());
      return $user->getFirstName()." ".$user->getLastName()." (".$user->getUsername().")";
    }
    public function getUpdatedByUser() {
      $user=Doctrine::getTable('SfGuardUser')->findOneBy('id',$this->getUpdatedBy());
      return $user->getFirstName()." ".$user->getLastName()." (".$user->getUsername().")";
    }
    public function getCreatedAtTxt() {
      return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
    }
    public function getUpdatedAtTxt() {
     return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
    }
}
