<?php

/**
 * InvAjusteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvAjusteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvAjusteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvAjuste');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
        return $query->select($rootAlias.'.*, e.nombre as ename, e.acronimo as emin, id.nombre as idname, iad.id as iadid, i.id as iid, i.producto_id as producto_id,
        p.id as pid, p.laboratorio_id, p.unidad_id, pc.id as pcid, pc.nombre')
          ->leftJoin($rootAlias . '.Empresa e')
          ->leftJoin($rootAlias . '.InvDeposito id')
          ->leftJoin($rootAlias . '.InvAjusteDet iad')
          ->leftJoin('iad.Inventario i')
          ->leftJoin('i.Producto p')
          ->leftJoin('p.ProdCategoria pc')
          ->leftJoin('p.ProdCompuesto pcomp');
    }
}