<?php

/**
 * InvDepositoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvDepositoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvDepositoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvDeposito');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, e.nombre as ename, e.acronimo as emin')
        ->leftJoin($rootAlias . '.Empresa e');
    }
}
