<?php

/**
 * InventarioTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InventarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InventarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Inventario');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, CAST(cantidad AS UNSIGNED) as qty, e.nombre as ename, e.acronimo as emin, p.id as pid, p.nombre as pname, p.url_imagen as imagen,
       id.acronimo as idname, 
       p.serial as sname, p.costo_usd_1 as costo, p.precio_usd_8 as p8, p.util_usd_8 as util8,
       pc.id as pcid, pc.nombre as pcname, 
       idet.id as idetit, idet.fecha_venc as fvenc,
       pu.id as puid, pu.nombre as unit, pl.id as plid, pl.nombre as plname')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Producto p')
        ->leftJoin('p.ProdCategoria pc')
        ->leftJoin('p.ProdUnidad pu')
        ->leftJoin('p.ProdLaboratorio pl')
        ->leftJoin('p.ProdCompuesto pcomp')
        ->leftJoin($rootAlias . '.InvDeposito id')
        ->leftJoin($rootAlias . '.InventarioDet idet');
    }
}
