<?php

/**
 * InvEntradaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvEntradaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvEntradaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvEntrada');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, e.nombre as ename, e.acronimo as emin, id.nombre as idname, ied.id as iedid, i.id as iid, i.producto_id as producto_id,
      p.id as pid, p.laboratorio_id, p.unidad_id, pc.id as pcid, pc.nombre')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.InvDeposito id')
        ->leftJoin($rootAlias . '.InvEntradaDet ied')
        ->leftJoin('ied.Inventario i')
        ->leftJoin('i.Producto p')
        ->leftJoin('p.ProdCategoria pc')
        ->leftJoin('p.ProdCompuesto pcomp');
    }
}