<?php

/**
 * InventarioDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InventarioDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InventarioDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InventarioDet');
    }
}