<?php

/**
 * InvSalidaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvSalidaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvSalidaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvSalida');
    }
    public static function doSelectJoinOtros($query)
    {
        $rootAlias = $query->getRootAlias();
        return $query->select($rootAlias.'.*, e.nombre as ename, e.acronimo as emin, id.nombre as idname, isd.id as isdid, i.id as iid, i.producto_id as producto_id,
        p.id as pid, p.laboratorio_id, p.unidad_id, pc.id as pcid, pc.nombre')
          ->leftJoin($rootAlias . '.Empresa e')
          ->leftJoin($rootAlias . '.InvDeposito id')
          ->leftJoin($rootAlias . '.InvSalidaDet isd')
          ->leftJoin('isd.Inventario i')
          ->leftJoin('i.Producto p')
          ->leftJoin('p.ProdCategoria pc')
          ->leftJoin('p.ProdCompuesto pcomp');
    }
}