<?php

/**
 * InvSalidaDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvSalidaDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvSalidaDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvSalidaDet');
    }
}