<?php

/**
 * KardexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KardexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KardexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Kardex');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, CAST(cantidad AS UNSIGNED) as qty,
       e.id as eid, e.acronimo as emin, 
       p.id as pid, p.nombre as pname, p.serial as sname,
       id.id as idid, id.acronimo as idname')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Producto p')
        ->leftJoin($rootAlias . '.InvDeposito id')
        ->orderBy($rootAlias.'.fecha ASC');
    }
}