<?php

/**
 * NivelServicioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NivelServicioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NivelServicioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NivelServicio');
    }
}