<?php

/**
 * NotaEntregaDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaEntregaDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaEntregaDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaEntregaDet');
    }
}