<?php

/**
 * NotaCreditoDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaCreditoDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaCreditoDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaCreditoDet');
    }
}