<?php

/**
 * NotaDebitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaDebitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaDebitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaDebito');
    }
    public static function doSelectJoinOtros($query) {
        $rootAlias = $query->getRootAlias();

        return $query->select($rootAlias.'.*, p.full_name as pname, fp.acronimo as fpago, e.id as eid, e.nombre as ename, e.acronimo as emin,
        LPAD(ncontrol, 6, 0) as ncontrol, CAST(ncontrol AS UNSIGNED) as ninteger, FORMAT(REPLACE(monto, " ", ""), 4, "de_DE") as monto')
            ->leftJoin($rootAlias . '.Empresa e')
            ->leftJoin($rootAlias . '.Proveedor p')
            ->leftJoin($rootAlias . '.FormaPago fp');
    }
}