<?php

/**
 * NotaEntregaTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaEntregaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaEntregaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaEntrega');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, e.nombre as ename, e.acronimo as emin, f.id as fid, f.num_factura as fnum')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Factura f');
    }
}
