<?php

/**
 * NotaDebitoDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaDebitoDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaDebitoDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaDebitoDet');
    }
}