<?php

/**
 * NotaDebito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NotaDebito extends BaseNotaDebito
{
  public function getCoin() {
    if($this->getMoneda()==1) {
      return "BS";
    } else {
      return "USD";
    }
  }
  public function getFechaTxt() {
    return strtoupper(format_datetime($this->getFecha(), 'D', 'es_ES'));
  }
  public function getForPago() {
    return $this["fpago"];
  }
  public function getForPagoCoin() {
    return $this["fpago"]." ".$this->getCoin();
  }
  public function getEmpresaName() {
    return strtoupper($this["ename"]);
  }
  public function getCompany() {
    return strtoupper($this["emin"]);
  }
  public function getCoinMonto() {
    return $this->getCoin()." ".$this->getMonto();
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
  public function putProcesar($ccid) {
    $val=0;
    $nota_debito = Doctrine_Core::getTable('NotaDebito')->findOneBy('id', $this->getId());
    $cuentas_pagar= Doctrine_Core::getTable('CuentasPagar')->findOneBy('id', $ccid);

    $tasa=$cuentas_pagar->getTasaCambio();
    $ccfaltante=$cuentas_pagar->getMontoFaltante();
    $ncfaltante=$this->getMontoFaltante();
    $ncfaltantebs=$ncfaltante*$tasa;
    $moneda=2;

    if(($ccfaltante-$ncfaltante)>=0) {
      $desc=$cuentas_pagar->putPagar($ncfaltante,$ncfaltantebs,$moneda);
      $nota_debito->monto_faltante=0.0000;
      $nota_debito->estatus=2;
      $nota_debito->save();

      $nota_debito_det = new NotaDebitoDet();
      $nota_debito_det->nota_debito_id=$nota_debito->getId();
      $nota_debito_det->cuentas_pagar_id=$ccid;
      $nota_debito_det->monto=$ncfaltante;
      $nota_debito_det->descripcion=$desc;
      $nota_debito_det->save();
      $val=1;
    } else {
      $monto_new=number_format($ncfaltante-$ccfaltante, 4, '.', '');
      $desc=$cuentas_pagar->putPagar($ccfaltante);
      $nota_debito->monto_faltante=$monto_new;
      $nota_debito->estatus=1;
      $nota_debito->save();

      $nota_debito_det = new NotaDebitoDet();
      $nota_debito_det->nota_debito_id=$nota_debito->getId();
      $nota_debito_det->cuentas_pagar_id=$ccid;
      $nota_debito_det->monto=$ccfaltante;
      $nota_debito_det->descripcion=$desc;
      $nota_debito_det->save();
    }
    return $val;
  }

  public function putAnular($id) {
    $val=0;
    $nota_debito = Doctrine_Core::getTable('NotaDebito')->findOneBy('id', $this->getId());

    $nota_debito_det = Doctrine_Core::getTable('NotaDebitoDet')->findOneBy('id', $id);
    $nota_debito_det->anulado=1;
    $nota_debito_det->save();

    $cuentas_pagar = Doctrine_Core::getTable('CuentasPagar')->findOneBy('id', $nota_debito_det->getCuentasPagarId());
    $cuentas_pagar->putAnular($nota_debito_det->getMonto());

    $ncpendiente=number_float4($nota_debito->getMontoFaltante());
    $ncdmonto=number_float4($nota_debito_det->getMonto());
    $new_pendiente=number_format($ncpendiente+$ncdmonto, 4, '.', '');

    $nota_debito->monto_faltante=$new_pendiente;
    $nota_debito->estatus=1;
    $nota_debito->save();

  }
}
