<?php

/**
 * NotaCreditoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaCreditoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaCreditoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaCredito');
    }
    public static function doSelectJoinOtros($query) {
      $rootAlias = $query->getRootAlias();

      return $query->select($rootAlias.'.*, c.full_name as cname, fp.acronimo as fpago, e.id as eid, e.nombre as ename, e.acronimo as emin')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Cliente c')
        ->leftJoin($rootAlias . '.FormaPago fp');
    }
}
