<?php

/**
 * NotaEntrega
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NotaEntrega extends BaseNotaEntrega
{
  public function getCompany() {
    return $this["emin"];
  }
  public function getTotalCoin() {
    return "USD ".number_format(number_float2($this->getTotal()),4, '.', ',');
  }
  public function getPendienteCoin() {
    return "USD ".number_format(number_float2($this->getMontoFaltante()), 4, '.', ',');
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
}
