<?php

/**
 * OfertaTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfertaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfertaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Oferta');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, FORMAT(REPLACE(precio_usd, " ", ""), 4, "de_DE") as precio_usd, 
      e.nombre as ename, e.acronimo as emin, id.acronimo as idname')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.InvDeposito id');
    }
    public static function doSelectJoinOtros2($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, od.id as odid, i.id as iid')
        ->leftJoin($rootAlias.'.OfertaDet od')
        ->leftJoin('od.Inventario i')
        ->Where('i.deposito_id =?', '111')
        ->andWhere('i.activo =?', 1)
        ->andWhere('activo =?', 1)
        ->andWhere("fecha <= '".date("Y-m-d")."' AND fecha_venc >= '".date("Y-m-d")."' ")
        ->orderBy('i.cantidad ASC');
    }
}
