<?php

/**
 * OfertaImgTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfertaImgTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfertaImgTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OfertaImg');
    }
}