<?php

/**
 * OrdenCompraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenCompraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenCompraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdenCompra');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, e.nombre as ename, e.acronimo as emin, cl.id as clid, cl.full_name as cname, oce.id as oceid, oce.nombre as ocename')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.OrdenCompraEstatus oce')
        ->leftJoin($rootAlias . '.Cliente cl');
    }
    public static function doSelectJoinOtros2($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*')
        ->orderBy($rootAlias.'.created_at DESC');
    }
}