<?php

/**
 * OrdenCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OrdenCompra extends BaseOrdenCompra
{
  public function getCompany() {
    return $this["emin"];
  }
  public function getTotalCoin() {
    return "USD ".number_format(number_float22($this->getTotal()), 4, '.', ',');
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
  public function getUrlImagen() {
    $imagen="";
    $results = Doctrine_Query::create()
      ->select('ocd.id as ocid, ocd.inventario_id as invid, i.id as iid, p.id as pid, p.url_imagen as inv_img')
      ->from('OrdenCompraDet ocd')
      ->leftJoin('ocd.Inventario i')
      ->leftJoin('i.Producto p')
      ->where('ocd.orden_compra_id = ?', $this->getId())
      ->execute();

    foreach ($results as $result) {
      if(!empty($result["invid"])) {
        if(!empty($result["inv_img"])) {
          $imagen="/uploads/producto/".$result["inv_img"];
          break;
        }
      }
    }
    return $imagen;
  }
}

function number_float22($str) {
  $stripped = str_replace(' ', '', $str);
  $number = str_replace(',', '', $stripped);
  return floatval($number);
}
