<?php

/**
 * OrdenesCompraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenesCompraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenesCompraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdenesCompra');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, LPAD(ncontrol, 6, 0) as ncontrol, CAST(ncontrol AS UNSIGNED) as ninteger, FORMAT(REPLACE(total, " ", ""), 4, "de_DE") as totalf, e.nombre as ename, e.acronimo as emin,
      cc.id as ccid, cc.ncontrol as cncontrol')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.CotizacionCompra cc');
    }
}