<?php

/**
 * Otros
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Otros extends BaseOtros
{
  public function getCompany() {
    return $this["emin"];
  }
  public function getValorNew() {
    return "Bs ".$this["valorFormat"];
  }
  public function getTipoTasa() {
    if($this->getNombre()=="T01") {
      return "TASA DE MEDICAMENTOS";
    } else if($this->getNombre()=="T02"){
      return "TASA DE MISCELANEOS";
    } else {
      return "TASA DEL DIA";
    }
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
}
