<?php

/**
 * OtrosTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OtrosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OtrosTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Otros');
    }
    public static function doSelectJoinOtros($query) {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, FORMAT(REPLACE(valor, " ", ""), 4, "de_DE") as valorFormat, e.nombre as ename, e.acronimo emin')
        ->leftJoin($rootAlias . '.Empresa e');
    }
}
