<?php

/**
 * ProductoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Producto');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, FORMAT(REPLACE(costo_usd_1, " ", ""), 4, "de_DE") as costo_format, 
      i.cantidad as qty, i.activo as iact, i.deposito_id as deposito_id, pc.id as pcid, pc.nombre as pcname,
      pu.id as puid, pu.nombre as puname, pl.id as plid, pl.nombre as plname')
        ->leftJoin($rootAlias . '.Inventario i')
        ->leftJoin($rootAlias . '.ProdUnidad pu')
        ->leftJoin($rootAlias . '.ProdLaboratorio pl')
        ->leftJoin($rootAlias . '.ProdCompuesto pcomp')
        ->leftJoin($rootAlias . '.ProdCategoria pc');
    }
    public static function doSelectJoinOtros2($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, i.cantidad as qty, i.activo as iact, i.deposito_id as deposito_id, 
      pc.id as pcid, pc.nombre as pcname')
        ->leftJoin($rootAlias . '.Inventario i')
        ->leftJoin($rootAlias . '.ProdCategoria pc')
        ->where('i.deposito_id=111');
    }
}
