<?php

/**
 * ProdUnidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProdUnidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProdUnidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProdUnidad');
    }
}