<?php

/**
 * ProdCompuestoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProdCompuestoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProdCompuestoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProdCompuesto');
    }
}