<?php

/**
 * ProdCategoria
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProdCategoria extends BaseProdCategoria
{
  public function  __toString()
  {
      return sprintf('%s', $this->getNombre());
  }
  public function getCodFull() {
    if(strlen($this->getCodigoFull())>0) {
      return $this->getCodigoFull();
    } else {
      if (strpos($this->getNombre(), '/') !== false) {
        $arreglo=explode('/', $this->getNombre());
        $cod=""; $j=0; $i=0; $nombre="";
        foreach ($arreglo as $arr) {
          if($j==0) {
            $nombre=$arr;
          } else {
            $nombre=$nombre."/".$arr;
          }
          $dets = Doctrine_Core::getTable('ProdCategoria')
            ->createQuery('a')
            ->select('nombre, codigo')
            ->Where("nombre LIKE '$nombre'")
            ->execute();
          foreach($dets as $det) {
            if($i==0) {
              $cod=str_pad($det->getCodigo(), 2, '0', STR_PAD_LEFT);
            } else {
              $cod=str_pad($cod, 2, '0', STR_PAD_LEFT)."-".str_pad($det->getCodigo(), 2, '0', STR_PAD_LEFT);
            }
            $i++;
          }
          $j++;
        }
        $cat=Doctrine::getTable('ProdCategoria')->findOneBy('id',$this->getId());
        $cat->codigo_full=$cod;
        $cat->save();
        return $cat->getCodigoFull();
      } else {
        $cat=Doctrine::getTable('ProdCategoria')->findOneBy('id',$this->getId());
        $cat->codigo_full=str_pad($this->getCodigo(), 2, '0', STR_PAD_LEFT);
        $cat->save();
        return $cat->getCodigoFull();
      }
    }
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
}
