<?php

/**
 * ProdCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProdCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProdCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProdCategoria');
    }
}