<?php

/**
 * ProdVendidosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProdVendidosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProdVendidosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProdVendidos');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      //return $query->select($rootAlias.'.*, CAST(cantidad AS UNSIGNED) as qty,
      return $query->select($rootAlias.'.id as rid, '.$rootAlias.'.oferta as oferta, SUM('.$rootAlias.'.cantidad) as qty, 
      FORMAT(SUM(CAST(price_tot AS DECIMAL(10,4))), 4, "de_DE") as total,
       e.id as eid, e.acronimo as emin, 
       p.id as pid, p.nombre as pname, p.serial as sname,
       id.id as idid, id.acronimo as idname, 
       pc.id as pcid, pc.nombre as pcname,
       pu.id as puid, pu.nombre as unit,
       plab.id as plabid, plab.descripcion as labname, plab.nombre as labnombre')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Producto p')
        ->leftJoin($rootAlias . '.InvDeposito id')
        ->leftJoin('p.ProdCategoria pc')
        ->leftJoin('p.ProdUnidad pu')
        ->leftJoin('p.ProdLaboratorio plab')
        ->Where($rootAlias.'.anulado = 0')
        ->groupBy($rootAlias.'.oferta, '.$rootAlias.'.producto_id')
        ;
    }
    public static function doSelectJoinRanking($query)
    {
      $rootAlias = $query->getRootAlias();
      //return $query->select($rootAlias.'.*, CAST(cantidad AS UNSIGNED) as qty,
      return $query->select($rootAlias.'.id as rid, SUM('.$rootAlias.'.cantidad) as qty, 
      FORMAT(SUM(CAST(price_tot AS DECIMAL(10,4))), 4, "de_DE") as total,
       e.id as eid, e.acronimo as emin, 
       p.id as pid,
       id.id as idid, id.acronimo as idname,
       pc.id as pcid,
       pu.id as puid,
       c.id as cid, c.full_name as cname, c.doc_id as docid')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Producto p')
        ->leftJoin($rootAlias . '.InvDeposito id')
        ->leftJoin($rootAlias . '.Cliente c')
        ->leftJoin('p.ProdCategoria pc')
        ->leftJoin('p.ProdUnidad pu')
        ->Where($rootAlias.'.anulado = 0')
        ->groupBy($rootAlias.'.empresa_id, '.$rootAlias.'.deposito_id, '.$rootAlias.'.cliente_id');
    }
}