<?php

/**
 * Proveedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Proveedor extends BaseProveedor
{
    public function  __toString()
  {
      return sprintf('%s', $this->getFullName()." [".$this->getDocId()."]");
  }
/*  public function getCompany() {
    return $this["emin"];
  }*/
  public function getTipoTxt() {
    if($this->getTipo()=="factura_compra") {
      return "FACTURA DE COMPRAS";
    } else if($this->getTipo()=="factura_gasto") {
      return "FACTURA DE GASTOS";
    } else {
      return "F. COMPRAS Y F. GASTOS";
    }
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
}
