<?php

/**
 * ReciboPagoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReciboPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReciboPagoTable
     */
    public static function getInstance(){
      return Doctrine_Core::getTable('ReciboPago');
    }
    public static function doSelectJoinOtros($query) {
      $rootAlias = $query->getRootAlias();

      return $query->select($rootAlias.'.*, c.full_name as cname, fp.acronimo as fpago, cc.id as ccid,
      f.id as fid, f.num_factura as fnum, f.ndespacho as fdespacho, ne.id as neid, ne.ncontrol as nenum, e.id as eid, e.nombre as ename, e.acronimo as emin')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Cliente c')
        ->leftJoin($rootAlias . '.FormaPago fp')
        ->leftJoin($rootAlias . '.CuentasCobrar cc')
        ->leftJoin('cc.Factura f')
        ->leftJoin('cc.NotaEntrega ne');
    }
}
