<?php

/**
 * ReciboPagoCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ReciboPagoCompra extends BaseReciboPagoCompra
{
  public function getCoin() {
    if($this->getMoneda()==1) {
      return "BS";
    } else {
      return "USD";
    }
  }
 
  public function getFechaTxt() {
    return strtoupper(format_datetime($this->getFecha(), 'D', 'es_ES'));
  }
  public function getForPago() {
    return $this["fpago"];
  }
  public function getForPagoCoin() {
    return $this["fpago"]." ".$this->getCoin();
  }
  public function getEmpresaName() {
    return strtoupper($this["ename"]);
  }
  public function getCompany() {
    return strtoupper($this["emin"]);
  }
  public function getCoinMonto() {
    return $this->getCoin()." ".$this->getMonto();
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
  public function getTotalbs() {
    return "BsS ".number_format(number_float2233($this->getMonto2()), 4, ',', ' ');
  }
  public function getNbanco() {
    return $this["bnombre"];
  }
}
