<?php

/**
 * Retenciones
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Retenciones extends BaseRetenciones
{
  public function getTipoTxt() {
    if($this->getTipo()==1) {
      return "IVA";
    } else if($this->getTipo()==2) {
      return "ISLR";
    } else {
      return "TIMBRE FISCAL";
    }
  }
  public function getEmpresaName() {
    return strtoupper($this["ename"]);
  }
  public function getCompany() {
    return strtoupper($this["emin"]);
  }
  public function getClienteName() {
    return strtoupper($this["cname"]);
  }
  public function getFechaTxt() {
    return strtoupper(format_datetime($this->getFecha(), 'D', 'es_ES'));
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
}
