<?php

/**
 * RetencionesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RetencionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RetencionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Retenciones');
    }
    public static function doSelectJoinOtros($query) {
      $rootAlias = $query->getRootAlias();

      return $query->select($rootAlias.'.*, c.full_name as cname, cc.id as ccid,
      f.id as fid, f.num_factura as fnum, e.id eid, e.nombre as ename, e.acronimo as emin')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Cliente c')
        ->leftJoin($rootAlias . '.CuentasCobrar cc')
        ->leftJoin('cc.Factura f');
    }
}
