<?php

/**
 * SafetyStockFarmaciaConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SafetyStockFarmaciaConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SafetyStockFarmaciaConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SafetyStockFarmaciaConfig');
    }
}