<?php

/**
 * SafetyStockFarmaciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SafetyStockFarmaciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SafetyStockFarmaciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SafetyStockFarmacia');
    }
}