<?php

/**
 * ServerNameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServerNameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServerNameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServerName');
    }
}