<?php

/**
 * ServerConfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServerConfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServerConfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServerConf');
    }
}