<?php

/**
 * TrasladoDetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrasladoDetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrasladoDetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrasladoDet');
    }
}