<?php

/**
 * TrasladoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrasladoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrasladoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Traslado');
    }
    public static function doSelectJoinOtros($query)
    {
      $rootAlias = $query->getRootAlias();
      return $query->select($rootAlias.'.*, e.nombre as ename, e2.nombre as e2name, id.nombre as idname, id2.nombre as id2name')
        ->leftJoin($rootAlias . '.Empresa e')
        ->leftJoin($rootAlias . '.Empresa2 e2')
        ->leftJoin($rootAlias . '.InvDeposito id')
        ->leftJoin($rootAlias . '.InvDeposito2 id2');
    }
}
