<?php

/**
 * Traslado
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Traslado extends BaseTraslado
{
  public function getEmpresaOrigen() {
    return $this["ename"];
  }
  public function getEmpresaDestino() {
    return $this["e2name"];
  }
  public function getDepositoOrigen() {
    return $this["idname"];
  }
  public function getDepositoDestino() {
    return $this["id2name"];
  }
  public function getCreatedAtTxt() {
    return format_datetime($this->getCreatedAt(), 'f', 'es_ES');
  }
  public function getUpdatedAtTxt() {
    return format_datetime($this->getUpdatedAt(), 'f', 'es_ES');
  }
}
