<?php

/**
 * TurnoverTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TurnoverTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TurnoverTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Turnover');
    }
}