generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProdCategoria
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          prod_categoria
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _index:
           label: indice
           credentials: [[farmacia, cat1, cat2, cat3]]
        _edit:
           label: editar
           credentials: [[farmacia, cat1, cat2]]
        _delete:
           label: eliminar
           credentials: [[farmacia, cat1]]
        _new:
           label: nuevo
           credentials: [[farmacia, cat1, cat2]]
        _show:
           label: mostrar
           credentials: [[farmacia, cat1, cat2, cat3]]
        _save:
           label: guardar
           credentials: [[farmacia, cat1, cat2]]
        _save_and_add:
           label: guardar y agregar nuevo
           credentials: [[farmacia, cat1, cat2]]
        _list:
           label: listado
           credentials: [[farmacia, cat1, cat2, cat3]]
        _reset:
           label: borrar filtros
           credentials: [[farmacia, cat1, cat2, cat3]]
      fields:
        url_imagen: {label: Imagen, tipo: url_imagen}
        nombre: {label: Nombre}
        codigo: {label: Codigo}
        codigo_full: {label: Codigo}
        CodFull: {label: Codigo, is_real: true}
        descripcion: {label: Descripcion}
        created_at: {label: Dia de Creacion, tipo: "fecha_two"}
        updated_at: {label: Ult. Actualizacion, tipo: "fecha_two"}
        created_by: {label: Creado por}
        updated_by: {label: Actualizado por}
        CreatedAtTxt: {label: Creado}
        UpdatedAtTxt: {label: Ult. Act}
        Creator: {label: Creado por}
        Updator: {label: Act. por}
        creado_por: {label: Creado por}
        updated_por: {label: Actualizado por}
      list:
        title: Categorias nn listado nn prod_categoria
        display: [CodFull, =nombre, created_at, updated_at]
        sort: [updated_at, desc]
        batch_actions: {}
      filter:
        display: [nombre, codigo_full, descripcion]
      form:
        display:
          requeridos: [codigo, nombre, url_imagen, _blank3, descripcion, _mask]
      edit:
        title:   Categorias nn editar nn prod_categoria
        actions:
          _list: ~
          _new: ~
          _show: ~
          _save: ~
      new:
        title:   Categorias nn nuevo nn prod_categoria
        actions:
          _list: ~
          _save: ~
      show:
        title:   Categorias nn detalle nn prod_categoria
        display:
          requeridos: [CodFull, nombre, url_imagen, _blank3, descripcion]
          otros:      [Creator, Updator, CreatedAtTxt, UpdatedAtTxt]
        actions:
          _list: ~
          _new: ~
          _edit: ~