generator:
  class: sfDoctrineGenerator
  param:
    model_class:           InvAjuste
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          inv_ajuste
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _index:
           label: indice
           credentials: [[farmacia, analistai, invaju1, invaju2, invaju3]]
        _edit:
           label: editar
           credentials: [[farmacia, analistai, invaju1, invaju2]]
        _delete:
           label: eliminar
           credentials: [[farmacia, analistai, invaju1]]
        _new:
           label: nuevo
           credentials: [[farmacia, analistai, invaju1, invaju2]]
        _show:
           label: mostrar
           credentials: [[farmacia, analistai, invaju1, invaju2, invaju3]]
        _save:
           label: guardar
           credentials: [[farmacia, analistai, invaju1, invaju2]]
        _save_and_add:
           label: guardar y agregar nuevo
           credentials: [[farmacia, analistai, invaju1, invaju2]]
        _list:
           label: listado
           credentials: [[farmacia, analistai, invaju1, invaju2, invaju3]]
        _reset:
           label: borrar filtros
           credentials: [[farmacia, analistai, invaju1, invaju2, invaju3]]
        _add_item:
           label: agregar item
           credentials: [[farmacia, analistai, invaju1, invaju2]]
        _reporteFirst:
           label: REPORTE DE AJUSTE INV.
           target: _blank
           credentials: [[farmacia, analistai, invaju1, invaju2, invaju3]]
      fields:
        empresa_id: {label: Empresa}
        deposito_id: {label: Deposito}
        EmpresaName: {label: Empresa, is_real: true}
        DepositoName: {label: Deposito, is_real: true}
        anulado: {label: Estatus}
        Estatus: {label: Estatus, is_real: true}
        created_at: {label: Dia de Creacion, tipo: "fecha_two"}
        updated_at: {label: Ult. Actualizacion, tipo: "fecha_two"}
        created_by: {label: Creado por}
        updated_by: {label: Actualizado por}
        CreatedAtTxt: {label: Creado, is_real: true}
        UpdatedAtTxt: {label: Ult. Act}
        Creator: {label: Creado por}
        Updator: {label: Act. por}
        creado_por: {label: Creado por}
        updated_por: {label: Actualizado por}
        company: {label: Empresa, is_real: true}
        id: {label: Codigo, is_real: true}
      list:
        title: Ajuste de Inv. nn listado nn inventario
        display: [id, company, DepositoName, created_at, _anulado]
        table_method: doSelectJoinOtros
        max_per_page: 20
        sort: [updated_at, desc]
        batch_actions:
          _reporteFirst: ~
      filter:
        display: [_mask_filter, created_at, updated_at, creado_por, updated_por]
      form:
        display:
          requeridos: [_mask, _det]
      edit:
        title:   Ajuste de Inv. nn ajuste nn inv_ajuste
        actions:
          _list: ~
          _new: ~
          _show: ~
          _save: ~
      new:
        title:   Ajuste de Inv. nn nuevo nn inv_ajuste
        actions:
          _list: ~
          _add_item: ~
          _save: ~
      show:
        title:   Ajuste de Inv. nn detalle nn inv_ajuste
        display:
          otros:      [Creator, Updator, CreatedAtTxt, UpdatedAtTxt, _mask_show]
        actions:
          _list: ~
          _new: ~