<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $full_name
 * @property string $email_address
 * @property string $clave
 * @property string $username
 * @property integer $cliente_id
 * @property string $url_imagen
 * @property string $cargo
 * @property string $algorithm
 * @property string $salt
 * @property string $password
 * @property boolean $is_active
 * @property boolean $is_super_admin
 * @property timestamp $last_login
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $Empresa
 * @property Cliente $Cliente
 * @property Doctrine_Collection $Caja
 * @property Doctrine_Collection $sfGuardUserPermission
 * @property Doctrine_Collection $sfGuardUserGroup
 * @property sfGuardRememberKey $RememberKeys
 * @property sfGuardForgotPassword $ForgotPassword
 * @property Doctrine_Collection $EmpresaUser
 * @property Doctrine_Collection $Kardex
 * @property Doctrine_Collection $ProdVendidos
 * @property Doctrine_Collection $ProdComprados
 * @property Carrito $Carrito
 * @property Doctrine_Collection $CajaUser
 * 
 * @method string                getFullName()              Returns the current record's "full_name" value
 * @method string                getEmailAddress()          Returns the current record's "email_address" value
 * @method string                getClave()                 Returns the current record's "clave" value
 * @method string                getUsername()              Returns the current record's "username" value
 * @method integer               getClienteId()             Returns the current record's "cliente_id" value
 * @method string                getUrlImagen()             Returns the current record's "url_imagen" value
 * @method string                getCargo()                 Returns the current record's "cargo" value
 * @method string                getAlgorithm()             Returns the current record's "algorithm" value
 * @method string                getSalt()                  Returns the current record's "salt" value
 * @method string                getPassword()              Returns the current record's "password" value
 * @method boolean               getIsActive()              Returns the current record's "is_active" value
 * @method boolean               getIsSuperAdmin()          Returns the current record's "is_super_admin" value
 * @method timestamp             getLastLogin()             Returns the current record's "last_login" value
 * @method Doctrine_Collection   getGroups()                Returns the current record's "Groups" collection
 * @method Doctrine_Collection   getPermissions()           Returns the current record's "Permissions" collection
 * @method Doctrine_Collection   getEmpresa()               Returns the current record's "Empresa" collection
 * @method Cliente               getCliente()               Returns the current record's "Cliente" value
 * @method Doctrine_Collection   getCaja()                  Returns the current record's "Caja" collection
 * @method Doctrine_Collection   getSfGuardUserPermission() Returns the current record's "sfGuardUserPermission" collection
 * @method Doctrine_Collection   getSfGuardUserGroup()      Returns the current record's "sfGuardUserGroup" collection
 * @method sfGuardRememberKey    getRememberKeys()          Returns the current record's "RememberKeys" value
 * @method sfGuardForgotPassword getForgotPassword()        Returns the current record's "ForgotPassword" value
 * @method Doctrine_Collection   getEmpresaUser()           Returns the current record's "EmpresaUser" collection
 * @method Doctrine_Collection   getKardex()                Returns the current record's "Kardex" collection
 * @method Doctrine_Collection   getProdVendidos()          Returns the current record's "ProdVendidos" collection
 * @method Doctrine_Collection   getProdComprados()         Returns the current record's "ProdComprados" collection
 * @method Carrito               getCarrito()               Returns the current record's "Carrito" value
 * @method Doctrine_Collection   getCajaUser()              Returns the current record's "CajaUser" collection
 * @method sfGuardUser           setFullName()              Sets the current record's "full_name" value
 * @method sfGuardUser           setEmailAddress()          Sets the current record's "email_address" value
 * @method sfGuardUser           setClave()                 Sets the current record's "clave" value
 * @method sfGuardUser           setUsername()              Sets the current record's "username" value
 * @method sfGuardUser           setClienteId()             Sets the current record's "cliente_id" value
 * @method sfGuardUser           setUrlImagen()             Sets the current record's "url_imagen" value
 * @method sfGuardUser           setCargo()                 Sets the current record's "cargo" value
 * @method sfGuardUser           setAlgorithm()             Sets the current record's "algorithm" value
 * @method sfGuardUser           setSalt()                  Sets the current record's "salt" value
 * @method sfGuardUser           setPassword()              Sets the current record's "password" value
 * @method sfGuardUser           setIsActive()              Sets the current record's "is_active" value
 * @method sfGuardUser           setIsSuperAdmin()          Sets the current record's "is_super_admin" value
 * @method sfGuardUser           setLastLogin()             Sets the current record's "last_login" value
 * @method sfGuardUser           setGroups()                Sets the current record's "Groups" collection
 * @method sfGuardUser           setPermissions()           Sets the current record's "Permissions" collection
 * @method sfGuardUser           setEmpresa()               Sets the current record's "Empresa" collection
 * @method sfGuardUser           setCliente()               Sets the current record's "Cliente" value
 * @method sfGuardUser           setCaja()                  Sets the current record's "Caja" collection
 * @method sfGuardUser           setSfGuardUserPermission() Sets the current record's "sfGuardUserPermission" collection
 * @method sfGuardUser           setSfGuardUserGroup()      Sets the current record's "sfGuardUserGroup" collection
 * @method sfGuardUser           setRememberKeys()          Sets the current record's "RememberKeys" value
 * @method sfGuardUser           setForgotPassword()        Sets the current record's "ForgotPassword" value
 * @method sfGuardUser           setEmpresaUser()           Sets the current record's "EmpresaUser" collection
 * @method sfGuardUser           setKardex()                Sets the current record's "Kardex" collection
 * @method sfGuardUser           setProdVendidos()          Sets the current record's "ProdVendidos" collection
 * @method sfGuardUser           setProdComprados()         Sets the current record's "ProdComprados" collection
 * @method sfGuardUser           setCarrito()               Sets the current record's "Carrito" value
 * @method sfGuardUser           setCajaUser()              Sets the current record's "CajaUser" collection
 * 
 * @package    ired.localhost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('full_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('clave', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => true,
             'length' => 200,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('cliente_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'unique' => true,
             'length' => 4,
             ));
        $this->hasColumn('url_imagen', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('cargo', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as Permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasMany('Empresa', array(
             'refClass' => 'EmpresaUser',
             'local' => 'user_id',
             'foreign' => 'empresa_id'));

        $this->hasOne('Cliente', array(
             'local' => 'cliente_id',
             'foreign' => 'id'));

        $this->hasMany('Caja', array(
             'refClass' => 'CajaUser',
             'local' => 'user_id',
             'foreign' => 'caja_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardForgotPassword as ForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('EmpresaUser', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Kardex', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ProdVendidos', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ProdComprados', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('Carrito', array(
             'local' => 'id',
             'foreign' => 'sf_guard_user_id'));

        $this->hasMany('CajaUser', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}