generator:
  class: sfDoctrineGenerator
  param:
    model_class:           FormaPago
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          forma_pago
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _index:
           label: indice
           credentials: [[sysadmin, forpag1, forpag2, forpag3]]
        _edit:
           label: editar
           credentials: [[sysadmin, forpag1, forpag2]]
        _delete:
           label: eliminar
           credentials: [[sysadmin, forpag1]]
        _new:
           label: nuevo
           credentials: [[sysadmin, forpag1, forpag2]]
        _show:
           label: mostrar
           credentials: [[sysadmin, forpag1, forpag2, forpag3]]
        _save:
           label: guardar
           credentials: [[sysadmin, forpag1, forpag2, forpag3]]
        _save_and_add:
           label: guardar y agregar nuevo
           credentials: [[sysadmin, forpag1, forpag2]]
        _list:
           label: listado
           credentials: [[sysadmin, forpag1, forpag2, forpag3]]
        _reset:
           label: borrar filtros
           credentials: [[sysadmin, forpag1, forpag2, forpag3]]
      fields:
        moneda: {label: Moneda}
        coin: {label: Moneda}
        coin: {label: Moneda, is_real: true}
        nombre: {label: Nombre}
        acronimo: {label: Acronimo}
        activo: {label: Estatus}
        estatus: {label: Estatus}
        descripcion: {label: Descripcion}
        created_at: {label: Dia de Creacion, tipo: "fecha_two"}
        updated_at: {label: Ult. Actualizacion, tipo: "fecha_two"}
        CreatedAtTxt: {label: Creado}
        UpdatedAtTxt: {label: Ult. Act}
        Creator: {label: Creado por}
        Updator: {label: Act. por}
        creado_por: {label: Creado por}
        updated_por: {label: Actualizado por}
      list:
        title: Formas de pago nn listado nn forma_pago
        display: [id, coin, nombre, _activo, updated_at]
        sort: [updated_at, desc]
        batch_actions: {}
      filter:
        display: [coin, nombre, activo, descripcion]
      form:
        display:
          requeridos: [_mask, moneda, nombre, acronimo, activo, descripcion]
      edit:
        title:   Formas de pago nn editar nn forma_pago
        actions:
          _list: ~
          _new: ~
          _show: ~
          _save: ~
      new:
        title:   Formas de pago nn nuevo nn forma_pago
        actions:
          _list: ~
          _save: ~
      show:
        title:   Formas de pago nn detalle nn forma_pago
        display:
          requeridos: [coin, nombre, acronimo, estatus, descripcion]
          otros:      [Creator, Updator, CreatedAtTxt, UpdatedAtTxt]
        actions:
          _list: ~
          _new: ~
          _edit: ~