generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ReciboPago
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          recibo_pago
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _index:
          label: indice
          credentials: [website]
        _edit:
          label: editar
          credentials: [website]
        _delete:
          label: eliminar
          credentials: [website]
        _anular:
          label: anular
          credentials: [website]
        _new:
          label: nuevo
          credentials: [website]
        _show:
          label: mostrar
          credentials: [website]
        _save:
          label: guardar
          credentials: [website]
        _save_and_add:
          label: guardar y agregar nuevo
          credentials: [website]
        _list:
          label: listado
          credentials: [website]
        _reset:
          label: borrar filtros
          credentials: [website]
        _reset:
          label: borrar filtros
          credentials: [website]
      fields:
        monto: {label: Monto USD, is_real: true}
        ncontrol: {label: Cod, is_real: true}
        descripcion: {label: Descripcion}
        cliente_id: {label: Cliente}
        clienteName: {label: Cliente, is_real: true}
        empresa_id: {label: Empresa}
        empresaName: {label: Empresa, is_real: true}
        num_recibo: {label: "N° de Voucher"}
        descripcion: {label: "+detalles"}
        fecha: {label: Fecha, tipo: "fecha_two"}
        fechaTxt: {label: Fecha, is_real: true}
        created_at: {label: Creado, tipo: "fecha_two"}
        updated_at: {label: Ult. Act., tipo: "fecha_two"}
        CreatedAtTxt: {label: Creado}
        UpdatedAtTxt: {label: Ult. Act}
        Creator: {label: Creado por}
        creado_por: {label: Creado por}
        Updator: {label: Act. por}
        forPagoCoin: {label: Forma de Pago, is_real: true}
        anulado: {label: Estatus}
        coin: {label: Moneda}
        company: {label: Empresa, is_real: true}
        detalle: {label: ""}
      list:
        title: Recibos de pago nn listado nn recibo_pago
        table_method: doSelectJoinOtros
        max_per_page: 20
        display: [ncontrol, company, clienteName, _documento, forPagoCoin, fechaTxt, monto, _anulado, _detalle]
        sort: [created_at, desc]
        batch_actions: {}
      filter:
        display: [id]
      form:
        display:
          requeridos: [_mask]
      edit:
        title:   Recibos de pago nn editar nn recibo_pago
        actions:
          _list: ~
          _new: ~
          _show: ~
          _save: ~
      new:
        title:   Recibos de pago nn nuevo nn recibo_pago
        actions:
          _list: ~
          _save: ~
      show:
        title:   Recibos de pago nn detalle nn recibo_pago
        display:
          otros:      [Creator, Updator, CreatedAtTxt, UpdatedAtTxt, _mask_show]
        actions:
          _list: ~
          _new: ~
