generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Traslado
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          traslado
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _index:
          label: indice
          credentials: [[farmacia, suppventa, tras1, tras2, tras3]]
        _edit:
          label: editar
          credentials: [[farmacia, suppventa, tras1, tras2]]
        _delete:
          label: eliminar
          credentials: [[farmacia, suppventa, tras1]]
        _anular:
          label: anular
          credentials: [[farmacia, suppventa, tras1]]
        _new:
          label: nuevo
          credentials: [[farmacia, suppventa, tras1, tras2]]
        _show:
          label: mostrar
          credentials: [[farmacia, suppventa, tras1, tras2, tras3]]
        _save:
          label: guardar
          credentials: [[farmacia, suppventa, tras1, tras2]]
        _save_and_add:
          label: guardar y agregar nuevo
          credentials: [[farmacia, suppventa, tras1, tras2]]
        _list:
          label: listado
          credentials: [[farmacia, suppventa, tras1, tras2, tras3]]
        _reset:
          label: borrar filtros
          credentials: [[farmacia, suppventa, tras1, tras2, tras3]]
        _print:
          label: imprimir
          credentials: [[farmacia, suppventa, tras1, tras2, tras3]]
        _add_item:
          label: agregar item
          credentials: [[farmacia, suppventa, tras1, tras2]]
      fields:
        ncontrol: {label: Codigo, is_real: true}
        empresaOrigen: {label: Empresa Origen, is_real: true}
        depositoOrigen: {label: Deposito Origen, is_real: true}
        empresaDestino: {label: Empresa Destino, is_real: true}
        depositoDestino: {label: Deposito Destino, is_real: true}
        created_at: {label: Dia de Creacion, tipo: "fecha_two"}
        updated_at: {label: Ult. Actualizacion, tipo: "fecha_two"}
        CreatedAtTxt: {label: Creado, is_real: true}
        UpdatedAtTxt: {label: Ult. Act}
        Creator: {label: Creado por}
        Updator: {label: Act. por}
        creado_por: {label: Creado por}
        updated_por: {label: Actualizado por}
        PendienteCoin: {label: Por Pagar, is_real: true}
        TotalCoin: {label: Total, is_real: true}
      list:
        title: Traslados nn listado nn traslado
        table_method: doSelectJoinOtros
        max_per_page: 20
        display: [id, empresaOrigen, depositoOrigen, empresaDestino, depositoDestino, CreatedAtTxt, _estatus]
        sort: [created_at, desc]
        batch_actions: {}
      filter:
        display: [_mask_filter, created_at, updated_at, creado_por, updated_por]
      form:
        display:
          filtros: [_mask]
      edit:
        title:   Traslados nn procesar nn traslado
        actions:
          _list: ~
          _new: ~
          _show: ~
          _save: ~
      new:
        title:   Traslados nn nuevo nn traslado
        actions:
          _list: ~
          _new: ~
      show:
        title:   Traslados nn detalle nn traslado
        display:
          otros:      [Creator, Updator, CreatedAtTxt, UpdatedAtTxt, _mask_show]
        actions:
          _list: ~
          _new: ~
