generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Compuesto
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          compuesto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _index:
           label: indice
           credentials: [[farmacia, com1, com2, com3]]
        _edit:
           label: editar
           credentials: [[farmacia, com1, com2]]
        _delete:
           label: eliminar
           credentials: [[farmacia, com1]]
        _new:
           label: nuevo
           credentials: [[farmacia, com1, com2]]
        _show:
           label: mostrar
           credentials: [[farmacia, com1, com2, com3]]
        _save:
           label: guardar
           credentials: [[farmacia, com1, com2]]
        _save_and_add:
           label: guardar y agregar nuevo
           credentials: [[farmacia, com1, com2]]
        _list:
           label: listado
           credentials: [[farmacia, com1, com2, com3]]
        _reset:
           label: borrar filtros
           credentials: [[farmacia, com1, com2, com3]]
      fields:
        nombre: {label: Nombre}
        descripcion: {label: Acronimo}
        created_at: {label: Dia de Creacion, tipo: "fecha_two"}
        updated_at: {label: Ult. Actualizacion, tipo: "fecha_two"}
        created_by: {label: Creado por}
        updated_by: {label: Actualizado por}
        CreatedAtTxt: {label: Creado}
        UpdatedAtTxt: {label: Ult. Act}
        Creator: {label: Creado por}
        Updator: {label: Act. por}
        creado_por: {label: Creado por}
        updated_por: {label: Actualizado por}
      list:
        title: Compuestos nn listado nn compuesto
        display: [=nombre, descripcion, created_at, updated_at]
        sort: [updated_at, desc]
        batch_actions: {}
      filter:
        display: [nombre, descripcion]
      form:
        display:
          requeridos: [nombre, descripcion, _mask]
      edit:
        title:   Compuestos nn editar nn compuesto
        actions:
          _list: ~
          _new: ~
          _show: ~
          _delete: ~
          _save: ~
      new:
        title:   Compuestos nn nuevo nn compuesto
        actions:
          _list: ~
          _save: ~
      show:
        title:   Compuestos nn detalle nn compuesto
        display:
          requeridos: [nombre, descripcion]
          otros:      [Creator, Updator, CreatedAtTxt, UpdatedAtTxt]
        actions:
          _list: ~
          _new: ~
          _edit: ~
          _delete: ~
