generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CuentasPagar
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          cuentas_pagar
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _index:
           label: indice
           credentials: [[cuentaspagar, contador, cuepag1, cuepag2, cuepag3]]
        _edit:
           label: editar
           credentials: [[cuentaspagar, contador, cuepag1, cuepag2]]
        _delete:
           label: eliminar
           credentials: [[cuentaspagar, contador, cuepag1]]
        _new:
           label: nuevo
           credentials: [[cuentaspagar, contador, cuepag1, cuepag2]]
        _show:
           label: mostrar
           credentials: [[cuentaspagar, contador, cuepag1, cuepag2, cuepag3]]
        _save:
           label: guardar
           credentials: [[cuentaspagar, contador, cuepag1, cuepag2]]
        _save_and_add:
           label: guardar y agregar nuevo
           credentials: [[cuentaspagar, contador, cuepag1, cuepag2]]
        _list:
           label: listado
           credentials: [[cuentaspagar, contador, cuepag1, cuepag2, cuepag3]]
        _reset:
           label: borrar filtros
           credentials: [[cuentaspagar, contador, cuepag1, cuepag2, cuepag3]]
        _saldoProveedores:
           label: SALDO A PROVEEDORES
           target: _blank
           credentials: [[cuentaspagar, contador, cuepag1, cuepag2, cuepag3]]           
      fields:
        doc: {label: Documento}
        empresaName: {label: Empresa, is_real: true}
        proveedorName: {label: Razon Social, is_real: true}
        Rif: {label: Rif, is_real: true}
        total: {label: Total, is_real: false}
        monto_faltante: {label: Restante, is_real: false}
        monto_pagado: {label: Pagado, is_real: false}
        estatus: {label: Estatus}
        created_at: {label: Dia de Creacion, tipo: "fecha_two"}
        updated_at: {label: Ult. Actualizacion, tipo: "fecha_two"}
        fecha: {label: Fecha de emision, tipo: "fecha_two"}
        CreatedAtTxt: {label: Fecha, is_real: true}
        dias: {label: D. Mora}
        doc: {label: Fact., is_real: true}
        fecha_recepcion: {label: Fecha de Recepcion, tipo: "fecha_two"}
      list:
        table_method: doSelectJoinOtros
        title: Cuentas por pagar nn listado nn cuentas_pagar
        display: [empresaName, proveedorName, _total, _monto_faltante, _monto_pagado, _estatus, _doc, _dias, _fecha_recepcion]
        sort: [created_at, desc]
        batch_actions:
          _saldoProveedores: ~
      filter:
        display: [_mask_filter, fecha, fecha_recepcion, created_at, updated_at]
      form:
        display:
          requeridos: [moneda, nombre, acronimo, activo, descripcion, _mask]
      edit:
        title:   Cuentas por pagar nn editar nn cuentas_pagar
        actions:
          _list: ~
          _new: ~
          _show: ~
          _delete: ~
          _save: ~
      new:
        title:   Cuentas por pagar nn nuevo nn cuentas_pagar
        actions:
          _list: ~
          _save: ~
      show:
        title:   Cuentas por pagar nn detalle nn cuentas_pagar
        display:
          requeridos: [coin, nombre, acronimo, estatus, descripcion]
          otros:      [Creator, Updator, created_at, updated_at]
        actions:
          _list: ~
          _new: ~
          _edit: ~
          _delete: ~
